- lib/build/cookieAndHeaders.d.ts
- lib/build/cookieAndHeaders.js
- lib/build/express.js
- lib/build/handshakeInfo.js
- lib/build/querier.d.ts
- lib/build/querier.js
- lib/build/session.d.ts
- lib/build/session.js
- lib/build/types.d.ts
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/ts/cookieAndHeaders.ts
- lib/ts/express.ts
- lib/ts/handshakeInfo.ts
- lib/ts/querier.ts
- lib/ts/session.ts
- lib/ts/types.ts
- lib/ts/utils.ts
- test/auth0Handler.test.js
- test/config.test.js
- test/deviceDriverInfo.test.js
- test/faunadb.test.js
- test/frontendIntegration/index.js
- test/handshake.test.js
- test/middleware.test.js
- test/querier.test.js
- test/session.test.js
- test/sessionExpress.test.js
Related issues:
- supertokens/supertokens-core#65
Changes:
- Normalising of all user input
- Removed `refreshTokenPath` and replaced it with `apiBasePath`
- Refactor of `init` code
- Added tests for checking of `init` and user configuration
Migration:
- Remove `refreshTokenPath` and use `apiBasePath` instead. The refresh API will always be `apiBasePath + "/session/refresh"`. This will require a change in the `init` config and the refresh API
Docs change - commit hash `c5dbab42672457b5d41b2ed63a486b3ba666e6bf` in main-website repo
> Changes to config

- lib/build/normalisedURLPath.d.ts
- lib/build/normalisedURLPath.js
- lib/build/querier.d.ts
- lib/build/querier.js
- lib/build/recipe/session/faunadb/sessionClass.d.ts
- lib/build/recipe/session/faunadb/sessionClass.js
- lib/build/recipe/session/faunadb/sessionRecipe.js
- lib/build/recipe/session/sessionClass.d.ts
- lib/build/recipe/session/sessionClass.js
- lib/build/recipe/session/sessionFunctions.js
- lib/build/recipe/session/sessionRecipe.js
- lib/build/recipe/session/types.d.ts
- lib/ts/normalisedURLPath.ts
- lib/ts/querier.ts
- lib/ts/recipe/session/faunadb/sessionClass.ts
- lib/ts/recipe/session/faunadb/sessionRecipe.ts
- lib/ts/recipe/session/sessionClass.ts
- lib/ts/recipe/session/sessionFunctions.ts
- lib/ts/recipe/session/sessionRecipe.ts
- lib/ts/recipe/session/types.ts
- test/handshake.test.js
- test/querier.test.js
- https://github.com/supertokens/supertokens-node/issues/18
- Adds `rid` to header for queries to `/recipe` or to `/recipe/*`
- Changes all session related APIs to be prefixed with `/recipe/*`
- Enforced use of `NormalisedUrlPath` for querying
- Removes `accessTokenValidity` from `Session` class (a TODO in the code)
- Corrects typo in code `accessTokenValiatity` => `accessTokenValidity`. Likewise for `refreshSessionValiatity`
- Use with core with CDI >= 2.4
> Conforms to cdi 2.4 for sessions

- lib/build/recipe/emailpassword/api/generatePasswordResetToken.js
- lib/build/recipe/emailpassword/api/utils.js
- lib/build/recipe/emailpassword/passwordResetFunctions.js
- lib/build/recipe/session/types.d.ts
- lib/build/recipe/session/utils.js
- lib/ts/recipe/emailpassword/api/generatePasswordResetToken.ts
- lib/ts/recipe/emailpassword/api/utils.ts
- lib/ts/recipe/emailpassword/passwordResetFunctions.ts
- lib/ts/recipe/session/types.ts
- lib/ts/recipe/session/utils.ts
- test/frontendIntegration/index.js
- test/middleware.test.js
- https://github.com/supertokens/supertokens-core/issues/98
- https://github.com/supertokens/supertokens-node/issues/38
- Removes the ability for the user to override the try refresh token callback in error handlers
- Changes to password reset email API to send the email after the response.
- Implements calling the supertokens API to send an email for password reset
- Users can no longer override the try refresh token callback in error handlers
> Misc changes

- test/emailpassword/emailverify.test.js
- test/utils.js
- 
- Adds emailVerifyTokenRequest() in utils for testing
- Tests added:
- generate token API:
- Call the API with valid input, email not verified
- Call the API with valid input, email verified and test error
- Call the API with no session and see the output (should be 401)
- Call the API with an expired access token and see that try refresh token is returned
- Provide your own email callback and make sure that is called
- email verify API:
- POST:
- Call the API with valid input
- Call the API with an invalid token and see the error
- token is not of type string from input
- provide a handlePostEmailVerification callback and make sure it's called on success verification
- GET:
- Call the API with valid input
- Call the API with no session and see the error
- Call the API with an expired …
> Email verification tests

- CHANGELOG.md
- lib/build/nextjs.d.ts
- lib/build/nextjs.js
- lib/ts/nextjs.ts
- test/nextjs.test.js
Expose a general middleware that can be used with any methods:
```js
import {superTokensNextWrapper} from "supertokens-node/nextjs";
// Example for Middleware
superTokensNextWrapper(async (next) => {
return SuperTokens.middleware(request, response, next)
}, request, response);
// Example for Verify Session
superTokensNextWrapper(async (next) => {
return SuperTokens.verifySession(request, response, next)
}, request, response);
```
Used in demo repo https://github.com/supertokens/supertokens-nextjs-demo/pull/5
> useSuperTokensFromNextJs

- lib/build/recipe/session/utils.js
- lib/ts/recipe/session/utils.ts
- test/config.test.js
if cookieSameSite is none, then the cookieSecure flag must be resulting in true. closes #63
> checking for cookie secure value when cookie samesite is "none"

- lib/build/recipe/thirdParty/api/signinup.js
- lib/build/recipe/thirdParty/providers/github.js
- lib/ts/recipe/thirdParty/api/signinup.ts
- lib/ts/recipe/thirdParty/providers/github.ts
- adding headers in signinup api to make sure response from provider is of type json
- using emails api to get primary email of user (provider: github)
> changes to make sure response from provider is of type json

- lib/build/recipe/thirdparty/api/authorisationUrl.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/ts/recipe/thirdparty/api/authorisationUrl.ts
- lib/ts/recipe/thirdparty/types.ts
- test/thirdparty/authorisationUrlFeature.test.js
per #94 this allows thirdparty providers to include dynamic params when constructing an authorisation url.
The params value type on the thirdparty now accepts a string or a function, where the function is provided the request object in order to read params, locales, etc.
This can be used for example to collect a user's domain, and use that in the `hd` parameter for google oauth.
Also updates a test.
> Accept dynamic params via function for authorisation url

- lib/build/recipe/emailpassword/api/generatePasswordResetToken.js
- lib/build/recipe/emailverification/api/generateEmailVerifyToken.js
- lib/ts/recipe/emailpassword/api/generatePasswordResetToken.ts
- lib/ts/recipe/emailverification/api/generateEmailVerifyToken.ts
In a serverless environment (specifically Vercel functions), the function program seems to stop shortly after a response is sent. This means that `createAndSendCustomEmail` does not always finish even though it is awaited. So usually an email is never sent even though the API responds "ok".
1. Define a custom async `createAndSendCustomEmail` for either password reset or email verify. In it, wait some (5?) seconds before resolving, and log something after waiting.
2. Deploy to Vercel
3. Open the realtime functions log in Vercel dashboard
4. Hit the API route to verify email or reset password. Note that the API response is "ok" but note in Vercel logs that your final log message after waiting is never printed.
I am not sure if this is a Vercel issue, lambda issue, or something else. …
> Fix email sending in serverless env

- CHANGELOG.md
- lib/build/recipe/session/faunadb/recipeImplementation.d.ts
- lib/build/recipe/session/faunadb/recipeImplementation.js
- lib/build/recipe/session/index.d.ts
- lib/build/recipe/session/index.js
- lib/build/recipe/session/recipeImplementation.d.ts
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionClass.d.ts
- lib/build/recipe/session/sessionClass.js
- lib/build/recipe/session/sessionFunctions.d.ts
- lib/build/recipe/session/sessionFunctions.js
- lib/build/recipe/session/types.d.ts
- lib/ts/recipe/session/faunadb/recipeImplementation.ts
- lib/ts/recipe/session/index.ts
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionClass.ts
- lib/ts/recipe/session/sessionFunctions.ts
- lib/ts/recipe/session/types.ts
- test/session.test.js
- Adds a new method to fetch all session info stored in the database for a given session handle
- Marks existing methods to fetch JWT and session data individually by session handle as deprecated
https://github.com/supertokens/supertokens-core/issues/255
> Add ability to fetch all session info from database using a session handle

- .circleci/config.yml
- .circleci/publish.sh
- CHANGELOG.md
- index.d.ts
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/version.ts
- nextjs/index.d.ts
- package-lock.json
- package.json
- recipe/emailpassword/index.d.ts
- recipe/emailverification/index.d.ts
- recipe/session/faunadb/index.d.ts
- recipe/session/index.d.ts
- recipe/thirdparty/index.d.ts
- recipe/thirdpartyemailpassword/index.d.ts
- redwood/index.d.ts
- test/with-typescript/index.ts
- test/with-typescript/tsconfig.json
- test/with-typescript/tslint.json
imports like:
```ts
import SuperTokens from 'supertokens-node';
```
throws the error `export * from "./lib/build" doesn't re-export the default export` . So for all the user facing  *.d.ts files, added:
```ts
import * as _default from "...";
export default _default;
```
- https://github.com/su…pertokens/supertokens-auth-react/issues/297
- updated `package.json` to try to build `test/with-typescript/index.ts` everytime after the source code is rebuild. If there is any issue with the default import statement, an error will be thrown.
- None
- In `package.json`
- In `package-lock.json`
- In `lib/ts/version.ts`
> fixes ts issue with default imports

- lib/build/recipe/session/sessionFunctions.js
- lib/build/recipe/session/types.d.ts
- lib/ts/recipe/session/sessionFunctions.ts
- lib/ts/recipe/session/types.ts
- test/session.test.js
Changes the response properties of getSessionInformation to be more readable and easy to understand:
- userDataInDatabase -> sessionData
- userDataInJWT -> jwtPayload
https://github.com/supertokens/docs/pull/80
Modified existing test cases to accommodate for the key changes, no new test cases needed. All existing tests pass (tested against core 3.5 and plugin-interface 2.8)
Documentation changes that are part of https://github.com/supertokens/docs/pull/80 will be modified to reflect these changes after this pull request is merged
- Along with the associated array in `lib/ts/version.ts`
- In `package.json`
- In `package-lock.json`
- In `lib/ts/version.ts`
- To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git …
> Rename properties of getSessionInformation response

- CHANGELOG.md
- lib/build/recipe/emailpassword/recipe.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/recipe/thirdparty/api/implementation.js
- lib/build/recipe/thirdparty/recipe.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/ts/recipe/emailpassword/recipe.ts
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/recipe/thirdparty/api/implementation.ts
- lib/ts/recipe/thirdparty/recipe.ts
- lib/ts/recipe/thirdparty/types.ts
We verify the email in the thirdparty sign in / up API if it is verified by the OAuth provider. Previously, this used to happen in the core itself, but that is going to be removed (see related issue). So we need to do it in the API.
- https://github.com/supertokens/supertokens-core/issues/295
The test for this is already done in one of the previous tests. Furthermore, I have confirmed that if the email verification code is missing in the sign in up API, the associated tests fail.
None
- To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
- If no such branch exists, then create one from the latest released branch.
> Thirdparty emailverification sign up change

- CHANGELOG.md
- lib/build/recipe/thirdparty/index.d.ts
- lib/build/recipe/thirdparty/index.js
- lib/build/recipe/thirdparty/recipeImplementation.d.ts
- lib/build/recipe/thirdparty/recipeImplementation.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.js
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/index.js
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/thirdPartyRecipeImplementation.d.ts
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/thirdPartyRecipeImplementation.js
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/ts/recipe/thirdparty/index.ts
- lib/ts/recipe/thirdparty/recipeImplementation.ts
- lib/ts/recipe/thirdparty/types.ts
- lib/ts/recipe/thirdpartyemailpassword/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/thirdPartyRecipeImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
- test/thirdparty/getUsersByEmailFeature.test.js
- test/thirdpartyemailpassword/getUsersByEmailFeature.test.js
Changes recipe interface for thirdparty and thirdpartyemailpassword to fetch users based on email.
- https://github.com/supertokens/supertokens-core/issues/277
- Fetched users based on email if none exist and check that the array length is 0
- Signed up users and checked that the users returned this time were correct.
- Deprecatation of `getUserByEmail` in thirdpartyemailpassword
- Addition of `getUsersByEmail` in thirdpartyemailpassword and thirdparty.
- To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
- If no such branch exists, then create one from the latest released branch.
> Thirdparty fetch email

- CHANGELOG.md
- lib/build/recipe/emailpassword/index.d.ts
- lib/build/recipe/emailpassword/index.js
- lib/build/recipe/emailpassword/recipe.d.ts
- lib/build/recipe/emailpassword/recipe.js
- lib/build/recipe/emailpassword/recipeImplementation.d.ts
- lib/build/recipe/emailpassword/recipeImplementation.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.js
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/emailPasswordRecipeImplementation.d.ts
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/emailPasswordRecipeImplementation.js
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/index.js
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/ts/recipe/emailpassword/index.ts
- lib/ts/recipe/emailpassword/recipe.ts
- lib/ts/recipe/emailpassword/recipeImplementation.ts
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/recipe/thirdpartyemailpassword/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/emailPasswordRecipeImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/index.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
- test/emailpassword/updateEmailPass.test.js
Adds updating of user's email or password recipe function in emailpassword and thirdpartyemailpassword recipes.
- https://github.com/supertokens/supertokens-core/issues/275
- Creates a user, changes their email and password, and then uses that to sign in successfully
- Recipe functions changes
- About `updateEmailOrPassword` in node js docs
- To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
- If no such branch exists, then create one from the latest released branch.
> adds new recipe function

- CHANGELOG.md
- lib/build/recipe/emailpassword/index.d.ts
- lib/build/recipe/emailpassword/index.js
- lib/build/recipe/emailpassword/recipe.d.ts
- lib/build/recipe/emailpassword/recipe.js
- lib/build/recipe/emailverification/index.d.ts
- lib/build/recipe/emailverification/index.js
- lib/build/recipe/emailverification/recipeImplementation.d.ts
- lib/build/recipe/emailverification/recipeImplementation.js
- lib/build/recipe/emailverification/types.d.ts
- lib/build/recipe/emailverification/types.js
- lib/build/recipe/thirdparty/index.d.ts
- lib/build/recipe/thirdparty/index.js
- lib/build/recipe/thirdparty/recipe.d.ts
- lib/build/recipe/thirdparty/recipe.js
- lib/build/recipe/thirdpartyemailpassword/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.js
- lib/build/recipe/thirdpartyemailpassword/recipe.d.ts
- lib/build/recipe/thirdpartyemailpassword/recipe.js
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/index.d.ts
- lib/ts/recipe/emailpassword/index.ts
- lib/ts/recipe/emailpassword/recipe.ts
- lib/ts/recipe/emailverification/index.ts
- lib/ts/recipe/emailverification/recipeImplementation.ts
- lib/ts/recipe/emailverification/types.ts
- lib/ts/recipe/thirdparty/index.ts
- lib/ts/recipe/thirdparty/recipe.ts
- lib/ts/recipe/thirdpartyemailpassword/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipe.ts
- test/emailpassword/emailverify.test.js
Adds email verification recipe functions for revoking tokens and for unverifying email
- https://github.com/supertokens/supertokens-core/issues/270
- Generate tokens, remove them, and try to verify yields error
- Verify and then unverify and check that email is unverified
- Recipe function changes
- About `unverifyEmail` and `revokeEmailVerificationTokens`
- To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
- If no such branch exists, then create one from the latest released branch.
> adds emailverification recipe functions

- test/jwt/config.test.js
- test/jwt/createJWTFeature.test.js
- test/jwt/getJWKS.test.js
- test/jwt/override.test.js
Adds a check to make sure the JWT tests run on CDI version 2.9 and above
Changes existing tests
None 
-   [x] ~~Changelog has been updated~~
-   [x] ~~`coreDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in `lib/ts/version.ts`~~
-   [x] ~~`frontendDriverInterfaceSupported.json` file has been updated (if needed)~~
-   [x] ~~Changes to the version if needed~~
-   ~~In `package.json`~~
-   ~~In `package-lock.json`~~
-   ~~In `lib/ts/version.ts`~~
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git …
> Add api version check to jwt tests

- test/frontendIntegration/index.html
Frontend tests now use axios-mock-adapter so I added it to the frontend integration `index.html`
-   supertokens/supertokens-website#85
CI test run will run using this HTML
N/A …
> Added axios-mock-adapter to the test html for frontend integration test to match supertokens-website

- lib/build/recipe/thirdparty/providers/github.js
- lib/ts/recipe/thirdparty/providers/github.ts
Uses `primary` instead of `isDefault` for the Github third party provider when getting the user's email
NA
NA
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose …
> Fix for Github provider when getting the users primary email

- CHANGELOG.md
- lib/build/recipe/thirdparty/providers/apple.js
- lib/ts/recipe/thirdparty/providers/apple.ts
- package-lock.json
- package.json
- test/config.test.js
- Uses `sub` claim for apple's userId 
- Uses apiGatewayPath and apiBasePath in paths for redirect_uri for apple
- Verifies id_token sent by apple using their jwks endpoint
-   https://github.com/supertokens/supertokens-core/issues/320
-   To know which one it is, run …
> uses sub in the id_token as thirdpartyId for apple & verifies id_token from apple's servers

- CHANGELOG.md
- lib/build/framework/awsLambda/framework.js
- lib/build/framework/hapi/framework.js
- lib/build/framework/koa/framework.d.ts
- lib/build/framework/koa/framework.js
- lib/ts/framework/awsLambda/framework.ts
- lib/ts/framework/hapi/framework.ts
- lib/ts/framework/koa/framework.ts
- test/framework/awsLambda.test.js
- test/framework/fastify.test.js
- test/framework/hapi.test.js
- test/framework/koa.test.js
- test/framework/loopback.test.js
- test/middleware2.test.js
- test/utils.js
Does not send a response if the user has already sent a response.
- https://github.com/supertokens/supertokens-node/issues/197
- Added tests for all frameworks to send a custom JSON response via an API ovrride and testing that.
None
-   To know which one it is, run …
> Response sent check

- CHANGELOG.md
- lib/build/framework/awsLambda/framework.d.ts
- lib/build/framework/awsLambda/framework.js
- lib/build/framework/awsLambda/index.d.ts
- lib/ts/framework/awsLambda/framework.ts
AWS lambda middleware will return `404` response if the API route is not served by the middleware and user has not passed a handler.
-   #196
-   [ ] If have added a new web framework, update the `add-ts-no-check.js` file to include that
-   [ ] If added a new recipe / …
> AWS Lambda API route not found update

- CHANGELOG.md
- lib/build/querier.d.ts
- lib/build/querier.js
- lib/build/supertokens.js
- lib/ts/querier.ts
- lib/ts/supertokens.ts
- test/querier.test.js
Takes into account the path supplied in the connectionURI when querying the core
-   https://github.com/supertokens/supertokens-node/issues/252
Added unit tests
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then …
> adds support for core base path

- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/backwardCompatibility/index.d.ts
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/backwardCompatibility/index.js
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/index.d.ts
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/index.js
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/smtp/index.d.ts
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/smtp/index.js
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/smtp/serviceImplementation/emailVerificationServiceImplementation.d.ts
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/smtp/serviceImplementation/emailVerificationServiceImplementation.js
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/smtp/serviceImplementation/index.d.ts
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/smtp/serviceImplementation/index.js
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/smtp/serviceImplementation/passwordlessServiceImplementation.d.ts
- lib/build/recipe/thirdpartypasswordless/emaildelivery/services/smtp/serviceImplementation/passwordlessServiceImplementation.js
- lib/build/recipe/thirdpartypasswordless/recipe.d.ts
- lib/build/recipe/thirdpartypasswordless/recipe.js
- lib/build/recipe/thirdpartypasswordless/types.d.ts
- lib/build/recipe/thirdpartypasswordless/utils.js
- lib/ts/recipe/thirdpartypasswordless/emaildelivery/services/backwardCompatibility/index.ts
- lib/ts/recipe/thirdpartypasswordless/emaildelivery/services/index.ts
- lib/ts/recipe/thirdpartypasswordless/emaildelivery/services/smtp/index.ts
- lib/ts/recipe/thirdpartypasswordless/emaildelivery/services/smtp/serviceImplementation/emailVerificationServiceImplementation.ts
- lib/ts/recipe/thirdpartypasswordless/emaildelivery/services/smtp/serviceImplementation/index.ts
- lib/ts/recipe/thirdpartypasswordless/emaildelivery/services/smtp/serviceImplementation/passwordlessServiceImplementation.ts
- lib/ts/recipe/thirdpartypasswordless/recipe.ts
- lib/ts/recipe/thirdpartypasswordless/types.ts
- lib/ts/recipe/thirdpartypasswordless/utils.ts
- refactored emailDelivery config for thirdpartypasswordless recipe
- added SMTP class for thirdpartypasswordless recipe
- refactored how email delivery config is return after normalisation. Only did the change so far for thirdpartypasswordless recipe. Reference comment: https://github.com/supertokens/supertokens-node/pull/274#discussion_r830789606
-  #274
> refactor: email sending service, Email Delivery and SMTP class changes for thirdpartypasswordless

- CHANGELOG.md
- lib/build/framework/utils.d.ts
- lib/build/framework/utils.js
- lib/build/nextjs.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/utils.ts
- lib/ts/nextjs.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/nextjs.test.js
- added `fromNextJS` property for next js request
-   #313
> fix: assertThatBodyParserHasBeenUsedForExpressLikeRequest

- test/emailpassword/emailDelivery.test.js
- test/passwordless/emailDelivery.test.js
- test/passwordless/smsDelivery.test.js
- test/thirdparty/emailDelivery.test.js
- test/thirdpartyemailpassword/emailDelivery.test.js
- test/thirdpartypasswordless/emailDelivery.test.js
- test/thirdpartypasswordless/smsDelivery.test.js
- added `process.env.TEST_MODE = "testing";` in the after hook for the tests in which the env gets changed to production
- for email delivery and sms delivery tests (passwordless and thirdpartypasswordless recipes), checking if the cdi version is >= 2.11
> refactor: email and sms delviery test changes

- CHANGELOG.md
- lib/build/recipe/thirdpartypasswordless/recipe.js
- lib/ts/recipe/thirdpartypasswordless/recipe.ts
Changes `getEmailForUserIdForEmailVerification` in thirdpartypasswordless to take into account passwordless user email as well in case the dev wants to customise the thirdpartypasswordless recipe's email verification functions to take into account passwordless users as well.
-   https://discord.com/channels/603466164219281420/987701400433725440/988016274443489300
> fix: thirdpartypasswordless email verification fix

- CHANGELOG.md
- lib/build/querier.js
- lib/ts/querier.ts
- test/usermetadata/updateUserMetadata.test.js
fix: content-type header for put requests
-   [User issue on discord](https://discord.com/channels/603466164219281420/990922887730987018)
Added extra test that uses unicode characters.
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the …
> fix: content-type header for put requests

- CHANGELOG.md
- lib/build/recipe/session/index.d.ts
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionClass.js
- lib/build/recipe/session/sessionFunctions.d.ts
- lib/build/recipe/session/sessionFunctions.js
- lib/build/recipe/session/types.d.ts
- lib/build/recipe/session/with-jwt/recipeImplementation.js
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionClass.ts
- lib/ts/recipe/session/sessionFunctions.ts
- lib/ts/recipe/session/types.ts
- lib/ts/recipe/session/with-jwt/recipeImplementation.ts
- test/framework/fastify.test.js
- test/framework/hapi.test.js
- test/framework/koa.test.js
- test/session.test.js
- test/sessionExpress.test.js
Makes changes to the session recipe for not throwing unauthorised error from functions that accept a session handle / access token and may not be working with the current session.
-   https://github.com/supertokens/backend/issues/83
TODO …
> fix!: makes changes to the session recipe functions

- CHANGELOG.md
- lib/build/recipe/session/sessionClass.js
- lib/ts/recipe/session/sessionClass.ts
- test/sessionExpress.test.js
When calling session.revokeSession, we used to clear the cookies only if the session used to exist in the core. This was an incorrect thing to do cause at the time of API session verification, the session did exist, so we should always clear the cookie when this function is called.
-   https://github.com/supertokens/supertokens-node/issues/343
Wrote a unit test that checks the output of calling the sign out API when the session is removed from the core before the sign out API is called
None
-   In …
> fixes issue https://github.com/supertokens/supertokens-node/issues/343

- CHANGELOG.md
- lib/build/recipe/session/index.d.ts
- lib/ts/recipe/session/index.ts
- test/with-typescript/index.ts
**NOTE**: I was unable to get the tests running properly from the information in CONTRIBUTING.md. (Also, it seems the `./startTestingEnv` script is deprecated.) The information may be outdated? Or perhaps I just need help in getting setup. Even so, I'm hoping this should be fine since these are just type definition changes.
These types will enable TS to know whether or not the value returned from `SessionWrapper.getSession` is guaranteed to be `defined`.
Provided 3 TypeScript `overload`s for `SessionWrapper.getSession`. These will improve TS types and IntelliSense for consumers of SuperTokens who use TS.
N/A
Check the types for the various overloads and verify that they are what you expect.
```typescript
import Session from"supertokens-node/recipe/session";
const sessionContainer1 = await …
```
> feat: Improve Type Definitions for `SessionWrapper.getSession`

- CHANGELOG.md
- lib/build/framework/express/framework.d.ts
- lib/build/framework/express/index.d.ts
- lib/build/framework/fastify/framework.js
- lib/build/recipe/session/framework/express.d.ts
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/fastify/framework.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/framework/fastify.test.js
- test/utils.js
- Updated fastify set cookie function to not use getCookieValueToSetInHeader function while setting cookie in header
> fix: fastify set-cookie header issue

- CHANGELOG.md
- lib/build/recipe/session/recipe.js
- lib/ts/recipe/session/recipe.ts
Add the request to the default user context of `verifySession`. This is used during testing + can be useful for the user in `overrideGlobalClaimValidators`
-   
-   In …
> feat(sessionclaims): verify session user context

- CHANGELOG.md
- lib/build/recipe/session/recipe.js
- lib/build/recipe/session/recipeImplementation.d.ts
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionClass.d.ts
- lib/build/recipe/session/sessionClass.js
- lib/ts/recipe/session/recipe.ts
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionClass.ts
- test/session.test.js
- test/utils.js
Use recipe functions with overrides in SessionContainer methods.
-   #366
Added a simple test case that checks if the override is applied (it fails without the fix)
N/A, bugfix …
> fix: use recipe functions with overrides in SessionContainer methods

- lib/build/recipe/emailverification/emailVerificationClaim.js
- lib/build/recipe/session/claimBaseClasses/booleanClaim.d.ts
- lib/build/recipe/session/claimBaseClasses/booleanClaim.js
- lib/build/recipe/session/claimBaseClasses/primitiveArrayClaim.d.ts
- lib/build/recipe/session/claimBaseClasses/primitiveArrayClaim.js
- lib/build/recipe/session/claimBaseClasses/primitiveClaim.d.ts
- lib/build/recipe/session/claimBaseClasses/primitiveClaim.js
- lib/build/recipe/session/with-jwt/recipeImplementation.js
- lib/ts/recipe/emailverification/emailVerificationClaim.ts
- lib/ts/recipe/session/claimBaseClasses/booleanClaim.ts
- lib/ts/recipe/session/claimBaseClasses/primitiveArrayClaim.ts
- lib/ts/recipe/session/claimBaseClasses/primitiveClaim.ts
- lib/ts/recipe/session/with-jwt/recipeImplementation.ts
- test/session/claims/primitiveArrayClaim.test.js
- test/session/claims/primitiveClaim.test.js
- test/session/claims/validateClaimsForSessionHandle.test.js
- test/session/claims/verifySession.test.js
- test/session/claims/withJWT.test.js
Changes discussed yesterday + comments on the PR:
- merged `hasFreshValue` into `hasValue`
- using id from claim for validators as well
- added `defaultMaxAge` to claims/validators
- checking `getSessionInformation` for undefined return value + fixed typing
-   
Updated&added tests
N/A
-   [x] Issue this PR against the latest non …
> feat(sessionclaims): review feedback

- CHANGELOG.md
- lib/build/recipe/session/api/implementation.js
- lib/build/recipe/session/api/signout.js
- lib/build/recipe/session/types.d.ts
- lib/ts/recipe/session/api/implementation.ts
- lib/ts/recipe/session/api/signout.ts
- lib/ts/recipe/session/types.ts
Just like how we changed the email verification API interface to accept session as input to the some of its functions, we should make similar changes to other APIs as well that "require" a session. So I have changed the signOut API in the session recipe to have this.
I also returned the session object from the refresh session API, since we are following a pattern that the API interface functions should return everything that it creates in it.
> adds session object as input / output to some of the api functions in session recipe

- lib/build/recipe/emailverification/index.js
- lib/ts/recipe/emailverification/index.ts
- test/emailpassword/emailverify.test.js
Fixing comment on the base PR
-   #278 
Added test 
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
-   If no …
> fix: fix the returned status of revokeEmailVerificationTokens for pwless users

- CHANGELOG.md
- lib/build/index.d.ts
- lib/build/supertokens.d.ts
- lib/build/supertokens.js
- lib/ts/index.ts
- lib/ts/supertokens.ts
- test/useridmapping/createUserIdMapping.test.js
- test/useridmapping/deleteUserIdMapping.test.js
Adds missing `force` param to `createUserIdMapping` and `deleteUserIdMapping` functions
-   In …
> fix: adds missing force param to userIdMapping functions

- lib/build/recipe/emailverification/emailVerificationClaim.js
- lib/ts/recipe/emailverification/emailVerificationClaim.ts
Refetch email verification info regularly, even if the user was verified before.
-   supertokens/supertokens-web-js/pull/64
-
Only an internally used optional param was added. …
> feat: refetch email verified claim based on maxAgeInSeconds (5 min default)

- CHANGELOG.md
- frontendDriverInterfaceSupported.json
Removed support for FDI 1.14
N/A
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
-   If no such branch …
> chore: remove support for fdi 1.14

- test/session/claims/createNewSession.test.js
Fixes running access token payload tests for older CDIs (which do not include null props in the payload)
-   
N/A test only change
N/A test only change
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the …
> test: fix tests old cdis

- CHANGELOG.md
- lib/build/recipe/emailverification/api/implementation.js
- lib/ts/recipe/emailverification/api/implementation.ts
rethrow generic errors in isEmailVerifiedGET and verifyEmailPOST
-   
-
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest …
> fix: rethrow generic errors in isEmailVerifiedGET and verifyEmailPOST

- CHANGELOG.md
- lib/build/recipe/emailverification/api/implementation.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/emailverification/api/implementation.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/emailpassword/emailverify.test.js
Updates session claims related to email verification in email verification token generation API as well - so that if someone is building a custom UI without our SDK on the frontend and they forget to call the get email verification API, then claims will still be updated correctly for them.
-   https://github.com/supertokens/supertokens-node/issues/419
Added test to query API and check if tokens are updated in the response
No change required
-   In …
> Email verification post session claim update

- CHANGELOG.md
- lib/build/recipe/session/sessionClass.d.ts
- lib/build/recipe/session/sessionClass.js
- lib/build/recipe/session/with-jwt/sessionClass.d.ts
- lib/build/recipe/session/with-jwt/sessionClass.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/session/sessionClass.ts
- lib/ts/recipe/session/with-jwt/sessionClass.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/session/with-jwt/sessionClass.test.js
- test/session/with-jwt/withjwt.test.js
- make mergeIntoAccessTokenPayload properly update the jwt payload
- use class methods instead of arrow functions defined on the instance
-   #423 
Added test cases:
- `SessionContainer.mergeIntoAccessTokenPayload ` should update JWT
- `SessionContainer.fetchAndSetClaim` should update JWT when setting claim value
- `SessionContainer.setClaimValue` should update JWT when setting claim value
- `SessionContainer.removeClaim` should update JWT when removing claim
- `Session.mergeIntoAccessTokenPayload` updates JWT (passed originally)
N/A, fix change
-   [x] `frontendDriverInterfaceSupported.json` file has been updated (if …
> fix: make mergeIntoAccessTokenPayload properly update the jwt payload

- lib/build/recipe/accountlinking/types.d.ts
- lib/build/recipe/dashboard/api/userdetails/userPasswordPut.d.ts
- lib/build/recipe/dashboard/api/userdetails/userPasswordPut.js
- lib/build/recipe/emailpassword/api/implementation.js
- lib/build/recipe/emailpassword/emaildelivery/services/backwardCompatibility/index.js
- lib/build/recipe/emailpassword/index.d.ts
- lib/build/recipe/emailpassword/index.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/recipe/thirdpartyemailpassword/api/emailPasswordAPIImplementation.js
- lib/build/recipe/thirdpartyemailpassword/api/implementation.js
- lib/build/recipe/thirdpartyemailpassword/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.js
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/ts/recipe/accountlinking/types.ts
- lib/ts/recipe/dashboard/api/userdetails/userPasswordPut.ts
- lib/ts/recipe/emailpassword/api/implementation.ts
- lib/ts/recipe/emailpassword/emaildelivery/services/backwardCompatibility/index.ts
- lib/ts/recipe/emailpassword/index.ts
- lib/ts/recipe/emailpassword/recipeImplementation.ts
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/recipe/thirdpartyemailpassword/api/emailPasswordAPIImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/api/implementation.ts
- lib/ts/recipe/thirdpartyemailpassword/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/emailPasswordRecipeImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/index.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
- test/with-typescript/index.ts
- EP recipe interface changes regarding account-linking
> Recipe interface changes regarding account-linking

- CHANGELOG.md
- lib/build/recipe/dashboard/api/userdetails/userPut.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/api/userdetails/userPut.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- User put API had an incorrect import for the thirdpartyemailpassword recipe resulting in a 500
-  
-   In …
> fix: Fix user put API importing incorrectly for thirdpartyemailpassword

- lib/build/recipe/passwordless/api/implementation.js
- lib/build/recipe/passwordless/types.d.ts
- lib/build/recipe/thirdpartypasswordless/api/implementation.js
- lib/build/recipe/thirdpartypasswordless/api/passwordlessAPIImplementation.js
- lib/build/recipe/thirdpartypasswordless/types.d.ts
- lib/ts/recipe/passwordless/api/implementation.ts
- lib/ts/recipe/passwordless/types.ts
- lib/ts/recipe/thirdpartypasswordless/api/implementation.ts
- lib/ts/recipe/thirdpartypasswordless/api/passwordlessAPIImplementation.ts
- lib/ts/recipe/thirdpartypasswordless/types.ts
- passwordless interface changes for account linking
> passwordless interface changes for account linking

- CHANGELOG.md
- lib/build/recipe/emailpassword/emaildelivery/services/backwardCompatibility/index.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/emailpassword/emaildelivery/services/backwardCompatibility/index.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/emailpassword/emailDelivery.test.js
If the user is overriding the sendEmail function in emailpassword recipe to change the input email, their change will not get reflected since our implementation calls the getUserById function which will reset their changed email. 
So we reassign the input email to the result of calling getUserById
Added one test for checking that a different email is mantained
> fixes bug - sendEmail

- CHANGELOG.md
- lib/build/recipe/dashboard/api/userdetails/userGet.js
- lib/build/recipe/dashboard/utils.d.ts
- lib/build/recipe/dashboard/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/api/userdetails/userGet.ts
- lib/ts/recipe/dashboard/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- Updates dashboard version to 0.3
- Updates user GET API in dashboard recipe to handle if the recipe for the user being fetched was not initialised
-   
None
- …
> fix: Update dashboard recipe user Get API

- lib/ts/framework/awsLambda/framework.ts
Fixed typo. This would cause Content-Type to be plain on Lambda with Middy.
> Fix awsLambda header typo

- lib/build/recipe/dashboard/recipe.d.ts
- lib/build/recipe/dashboard/utils.d.ts
- lib/build/recipe/dashboard/utils.js
- lib/build/supertokens.js
- lib/ts/recipe/dashboard/recipe.ts
- lib/ts/recipe/dashboard/utils.ts
- lib/ts/supertokens.ts
This PR adds logic to the SDK that automatically initialises the dashboard recipe if the user has not already initialised it when calling SuperTokens.init
-  
WIP
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then …
> feat: Add logic to initalise the dashboard recipe by default

- CHANGELOG.md
- lib/build/recipe/dashboard/api/signOut.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/api/signOut.ts
- lib/ts/version.ts
- package-lock.json
- package.json
Refactors dashboard sign out logic to check for the auth mode in the normalised config instead of manually checking for the api key 
-   
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch …
> refactor: Use auth mode instead of manually checking for api key in config

- CHANGELOG.md
- lib/build/supertokens.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/supertokens.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/frontendIntegration/index.js
- Removes the dashboard import from the supertokens class to fix an issue where importing a recipe without importing the package index would cause the server to crash
-   #513 
All existing tests pass
NA
-   To know which one it is, run find the latest released tag …
> fix: Removes dashboard import from supertokens class

- test/import.test.js
- test/utils.js
- Adds tests to make sure circular imports dont cause issues by importing every build file individually
- 
All existing tests pass and added new tests
NA
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the …
> chore: Add tests for circular imports

- CHANGELOG.md
- lib/build/framework/awsLambda/framework.js
- lib/build/framework/fastify/framework.js
- lib/build/framework/utils.js
- lib/build/recipe/dashboard/recipe.js
- lib/build/recipe/dashboard/utils.d.ts
- lib/build/recipe/dashboard/utils.js
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/awsLambda/framework.ts
- lib/ts/framework/fastify/framework.ts
- lib/ts/framework/utils.ts
- lib/ts/recipe/dashboard/recipe.ts
- lib/ts/recipe/dashboard/utils.ts
- lib/ts/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/framework/awsLambda.test.js
- test/framework/fastify.test.js
- test/framework/hapi.test.js
- test/framework/koa.test.js
- test/framework/loopback.test.js
- test/import.test.js
- test/utils.js
- test/utils.test.js
- Fixes getHeaderValue's logic to add case insensitivity
- Fixes an issue where Hapi returns 404 for all Dashboard recipe APIs
- Adds tests to check if circular imports causes issues
- Adds tests for reading headers in frameworks
-   #508 
-   #513 
Existing and new tests should pass
NA
-   [x] Issue this PR against the latest non …
> fix: Fix getHeaderValue case sensitivity, Hapi dashboard APIs 404

- lib/build/recipe/dashboard/api/implementation.js
- lib/ts/recipe/dashboard/api/implementation.ts
> Enable search only for CDI version above 2.20

- CHANGELOG.md
- coreDriverInterfaceSupported.json
- lib/build/recipe/openid/index.d.ts
- lib/build/recipe/openid/index.js
- lib/build/recipe/openid/recipeImplementation.js
- lib/build/recipe/openid/types.d.ts
- lib/build/recipe/session/index.d.ts
- lib/build/recipe/session/index.js
- lib/build/version.js
- lib/ts/recipe/openid/index.ts
- lib/ts/recipe/openid/recipeImplementation.ts
- lib/ts/recipe/openid/types.ts
- lib/ts/recipe/session/index.ts
- lib/ts/version.ts
- update createJWT in openId and session recipes 
- Update CDI version after merge
-   In …
> fix: update createJWT in openId and session recipes + CDI version

- lib/build/recipe/session/index.js
- lib/build/recipe/session/sessionRequestFunctions.js
- lib/ts/recipe/session/index.ts
- lib/ts/recipe/session/sessionRequestFunctions.ts
- test/framework/fastify.test.js
- test/framework/hapi.test.js
- test/framework/koa.test.js
- test/session.test.js
- test/session/claims/createNewSession.test.js
- test/session/claims/fetchAndSetClaim.test.js
- test/session/claims/removeClaim.test.js
- test/session/claims/setClaimValue.test.js
- test/sessionExpress.test.js
- Adding `iss` claim during `createNewSession`
- Updated/fixed tests
-   In …
> feat: add iss into access tokens + update/fix tests

- lib/build/recipe/accountlinking/index.d.ts
- lib/build/recipe/accountlinking/recipe.d.ts
- lib/build/recipe/accountlinking/recipe.js
- lib/build/recipe/accountlinking/recipeImplementation.js
- lib/build/recipe/accountlinking/types.d.ts
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/recipe/passwordless/types.d.ts
- lib/build/recipe/thirdparty/types.d.ts
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/build/recipe/thirdpartypasswordless/types.d.ts
- lib/ts/recipe/accountlinking/recipe.ts
- lib/ts/recipe/accountlinking/recipeImplementation.ts
- lib/ts/recipe/accountlinking/types.ts
- lib/ts/recipe/accountlinking/utils.ts
- lib/ts/recipe/emailpassword/api/implementation.ts
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/recipe/passwordless/types.ts
- lib/ts/recipe/thirdparty/api/implementation.ts
- lib/ts/recipe/thirdparty/types.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
- lib/ts/recipe/thirdpartypasswordless/types.ts
- Added `accountsAlreadyLinked` to canLink and link accounts functions
- Renamed `ACCOUNT_INFO_ALREADY_LINKED_WITH_ANOTHER_PRIMARY_USER_ID_ERROR` to `ACCOUNT_INFO_ALREADY_ASSOCIATED_WITH_ANOTHER_PRIMARY_USER_ID_ERROR`
- Replaced error throwing in unlink accounts with
```ts
{
status: "PRIMARY_USER_NOT_FOUND";
}
| {
status: "RESTART_FLOW_ERROR";
}
| {
status: "RECIPE_USER_NOT_FOUND";
}
```
- Calls `getPrimaryUserIdThatCanBeLinkedToRecipeUserId` inside `doPostSignUpAccountLinkingOperations` instead of `listUsersByAccountInfo`
- Moves logic of marking emails as verified after linking to linkAccounts
(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points …
> chore: Account linking general refactor

- lib/build/recipe/session/sessionFunctions.js
- lib/ts/recipe/session/sessionFunctions.ts
- test/framework/fastify.test.js
- test/framework/hapi.test.js
- test/framework/koa.test.js
- test/frontendIntegration/index.js
- test/middleware.test.js
- test/session.test.js
- it fixes a bug in sessionFunctions.ts setting the expirityTime in case we called the Core during session verification
- it updates the frontend integration server to mimic old behaviour using mergeIntoAccessTokenPayload
- Update some test assertions
-   Along with the associated array in …
> test: fix test failures in CI

- CHANGELOG.md
- lib/build/recipe/dashboard/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/dashboard.test.js
- Fixes an issue with Dashboard recipe initialisation which would result in API key based login always failing
- 
Added tests to make sure config gets normalised correctly
None …
> fix: Dashboard API key based login always failing with invalid API key

- CHANGELOG.md
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionRequestFunctions.js
- lib/build/recipe/session/types.d.ts
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionRequestFunctions.ts
- lib/ts/recipe/session/types.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- make loading access token from the request overrideable
-   Made the access token string optional in the overrideable `getSession` function
-   Moved checking if the access token is defined into the overrideable `getSession` function
-   
Will be tested manually by an example in the auth-react repo
N/A, it's only relevant in a very niche usecase
-   [x] Had installed and ran the …
> feat!: make loading access token from the request overrideable

- CHANGELOG.md
- lib/build/index.d.ts
- lib/build/index.js
- lib/build/supertokens.d.ts
- lib/build/supertokens.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/index.ts
- lib/ts/supertokens.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/userContext.test.js
- Added a helper function exported by the SuperTokens class that makes it easier to get the original request from the user context
- This reduces the boilerplate of always having to use `usercontext._default.request` and also allows the request to be strongly typed
-  
Added a test to make sure the new function works correctly
WIP
- …
> feat: Add a helper function to read the original request from the user context inside overrides

- CHANGELOG.md
- lib/build/framework/fastify/index.d.ts
- lib/build/framework/utils.d.ts
- lib/build/recipe/dashboard/api/apiKeyProtector.js
- lib/build/recipe/dashboard/error.d.ts
- lib/build/recipe/dashboard/error.js
- lib/build/recipe/dashboard/recipeImplementation.js
- lib/build/recipe/dashboard/types.d.ts
- lib/build/recipe/dashboard/utils.js
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/ts/recipe/dashboard/api/apiKeyProtector.ts
- lib/ts/recipe/dashboard/error.ts
- lib/ts/recipe/dashboard/recipeImplementation.ts
- lib/ts/recipe/dashboard/types.ts
- lib/ts/recipe/dashboard/utils.ts
- lib/ts/utils.ts
- Adds a new `admins` property to Dashboard init. This is a string array used to set the emails of the dashboard users that can perform write operations
- Changes the logic of session verification in the Dashboard APIs to return a 403 if the user's email is not present in the admins list (For non-GET APIs only). Note that we make an exception for the analytics POST API
- Changes the logic of shouldAllowAccess to throw a custom error if the user is not allowed to perform the action
- ...
WIP
-   In …
> feat: Allow users to set emails as admins when initialising the Dashboard recipe

- lib/build/recipe/multitenancy/recipe.d.ts
- lib/build/recipe/multitenancy/types.d.ts
- lib/ts/recipe/multitenancy/recipe.ts
- lib/ts/recipe/multitenancy/types.ts
> fix: tenantId compulsory in getAllowedDomainsForTenantId

- lib/build/recipe/multitenancy/api/implementation.js
- lib/build/recipe/multitenancy/index.d.ts
- lib/build/recipe/multitenancy/recipeImplementation.js
- lib/build/recipe/multitenancy/types.d.ts
- lib/build/recipe/thirdparty/api/authorisationUrl.js
- lib/build/recipe/thirdparty/api/signinup.js
- lib/build/recipe/thirdparty/index.d.ts
- lib/build/recipe/thirdparty/providers/configUtils.d.ts
- lib/build/recipe/thirdparty/providers/configUtils.js
- lib/build/recipe/thirdparty/recipeImplementation.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/build/recipe/thirdpartypasswordless/index.d.ts
- lib/build/recipe/thirdpartypasswordless/types.d.ts
- lib/ts/recipe/multitenancy/api/implementation.ts
- lib/ts/recipe/multitenancy/index.ts
- lib/ts/recipe/multitenancy/recipeImplementation.ts
- lib/ts/recipe/multitenancy/types.ts
- lib/ts/recipe/thirdparty/api/authorisationUrl.ts
- lib/ts/recipe/thirdparty/api/signinup.ts
- lib/ts/recipe/thirdparty/providers/configUtils.ts
- lib/ts/recipe/thirdparty/recipeImplementation.ts
- lib/ts/recipe/thirdparty/types.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/thirdPartyRecipeImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
- lib/ts/recipe/thirdpartypasswordless/recipeImplementation/index.ts
- lib/ts/recipe/thirdpartypasswordless/recipeImplementation/thirdPartyRecipeImplementation.ts
- lib/ts/recipe/thirdpartypasswordless/types.ts
> fix: handle tenant not found error

- lib/build/recipe/thirdparty/providers/bitbucket.js
- lib/build/recipe/thirdparty/providers/configUtils.js
- lib/build/recipe/thirdparty/providers/custom.js
- lib/build/recipe/thirdparty/providers/github.js
- lib/build/recipe/thirdparty/providers/gitlab.d.ts
- lib/build/recipe/thirdparty/providers/gitlab.js
- lib/build/recipe/thirdparty/providers/index.d.ts
- lib/build/recipe/thirdparty/providers/index.js
- lib/build/recipe/thirdparty/providers/linkedin.js
- lib/build/recipe/thirdparty/providers/utils.js
- lib/ts/recipe/thirdparty/providers/bitbucket.ts
- lib/ts/recipe/thirdparty/providers/configUtils.ts
- lib/ts/recipe/thirdparty/providers/custom.ts
- lib/ts/recipe/thirdparty/providers/github.ts
- lib/ts/recipe/thirdparty/providers/gitlab.ts
- lib/ts/recipe/thirdparty/providers/index.ts
- lib/ts/recipe/thirdparty/providers/linkedin.ts
- lib/ts/recipe/thirdparty/providers/utils.ts
> fix: bitbucket gitlab impl and other fixes

- CHANGELOG.md
- test/thirdparty/provider.config.test.js
provider tests and updated changelog
-   [ ] Had …
> fix: provider test and changelog

- CHANGELOG.md
- lib/build/recipe/dashboard/api/userdetails/userEmailVerifyGet.js
- lib/build/recipe/dashboard/api/userdetails/userEmailVerifyPut.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/api/userdetails/userEmailVerifyGet.ts
- lib/ts/recipe/dashboard/api/userdetails/userEmailVerifyPut.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/dashboard/userEmailVerifyGet.test.js
- Fixes an issue where the dashboard recipe was incorrectly passing the user context as the email when trying to check if an email is verified and when unverifying the email. This would result in the email as always being unverified on the frontend
-   #661 
Adds additional tests
NA
-   [ ] …
> fix: Fix issue of user dashboard showing email as unverified even if it is verified

- CHANGELOG.md
- lib/build/constants.d.ts
- lib/build/constants.js
- lib/build/querier.d.ts
- lib/build/querier.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/constants.ts
- lib/ts/querier.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/ratelimiting.test.js
- Adds logic to retry network calls if the core returns status 429
- 
Adds new tests …
> refactor: Add handling for when Saas returns 429 because of rate limiting

- test/auth-react-server/index.js
- test/frontendIntegration/index.js
> fix: Cicd fixes

- CHANGELOG.md
- lib/build/framework/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
Improve edge function compatibility by removing our `raw-body` dependency.
-   [Discord thread](https://discord.com/channels/603466164219281420/1141641603522494484)
Manual test by deploying to vercel
N/A
-   [ ] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, …
> refactor: replace raw-body dependency

- lib/build/recipe/thirdparty/providers/github.js
- lib/ts/recipe/thirdparty/providers/github.ts
> feat: Access token verification for GitHub #2

- lib/build/recipe/thirdparty/api/implementation.js
- lib/build/recipe/thirdparty/providers/custom.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/ts/recipe/thirdparty/api/implementation.ts
- lib/ts/recipe/thirdparty/providers/custom.ts
- lib/ts/recipe/thirdparty/types.ts
Adds a new optional function `validateAccessToken` to provider configs that allows users to validate the access token issued by third party providers during sign in or up
- 
WIP
WIP …
> feat: Add validateAccessToken for third party providers

- CHANGELOG.md
- lib/build/recipe/session/constants.d.ts
- lib/build/recipe/session/constants.js
- lib/build/recipe/session/index.js
- lib/build/recipe/session/recipeImplementation.d.ts
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionClass.js
- lib/build/recipe/session/sessionFunctions.js
- lib/build/recipe/session/sessionRequestFunctions.js
- lib/ts/recipe/session/constants.ts
- lib/ts/recipe/session/index.ts
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionClass.ts
- lib/ts/recipe/session/sessionFunctions.ts
- lib/ts/recipe/session/sessionRequestFunctions.ts
- test/accountlinking/session.test.js
- test/session/accessTokenVersions.test.js
- ignore protected props in createNewSession*
- moved some constants into the separate constants file in `Session`
-   
Modified existing tests
Done separately, some updates required
-   [ ] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, `createProvider` …
> feat: ignore protected props in createNewSession*

- lib/build/recipe/emailpassword/api/implementation.js
- lib/ts/recipe/emailpassword/api/implementation.ts
fix: add tenant id into password reset links
-   CI test failures
Already tested (caught in CI)
N/A, bugfix
-   [ ] Issue this …
> fix: add tenant id into password reset links

- CHANGELOG.md
- lib/build/recipe/jwt/api/implementation.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/jwt/api/implementation.ts
- lib/ts/recipe/jwt/recipeImplementation.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/jwt/getJWKS.test.js
> fix: Fix jwks body containing additional properties

- .github/workflows/test-edge-function.yml
- examples/aws/with-emailpassword/test/basic.test.js
- examples/express/with-emailpassword/test/basic.test.js
- examples/fastify/with-emailpassword/test/basic.test.js
- examples/hapi/with-emailpassword/test/basic.test.js
- examples/koa/with-emailpassword/test/basic.test.js
- examples/loopback/with-emailpassword/test/basic.test.js
- examples/nest/with-emailpassword/test/basic.test.js
- examples/next/with-emailpassword/config/appInfo.ts
- examples/next/with-emailpassword/netlify.toml
- examples/next/with-emailpassword/package-lock.json
- examples/next/with-emailpassword/package.json
- examples/next/with-emailpassword/test/basic.test.js
- updateLibInExample
> feat: add edge function testing

- CHANGELOG.md
- lib/build/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/config.test.js
fix: handle ec2 public urls as apiDomain
-   https://github.com/supertokens/supertokens-python/pull/449/files
- Added test that getTopLevelDomainForSameSiteResolution returns the right value
- Added a test checking that we set the right cookie settings based on that
N/A
-   [ ] update switch …
> fix: handle ec2 public urls as apiDomain

- lib/build/recipe/emailverification/api/implementation.js
- lib/build/recipe/emailverification/recipe.js
- lib/ts/recipe/emailverification/api/implementation.ts
- lib/ts/recipe/emailverification/recipe.ts
fix: revert optimization that made emailVerifyGET only update the claim if the value changes
-   
Manual testing - results in less emailVerifyGET calls.
+ TODO: https://github.com/supertokens/supertokens-node/issues/721
N/A …
> fix: revert optimization that made emailVerifyGET only update the claim if the value changes

- test/accountlinking/emailverificationapis.test.js
- test/emailpassword/emailverify.test.js
Updates test cases related to #722 
Solves #721 
- …
> test: update tests that check when the ev claim is updated

- test/framework/custom.test.js
test: update custom framework test to pass on node16
-   In …
> test: update custom framework test to pass on node16

- CHANGELOG.md
- lib/build/framework/awsLambda/framework.js
- lib/build/framework/custom/framework.js
- lib/build/framework/fastify/framework.js
- lib/build/framework/fastify/index.d.ts
- lib/build/framework/koa/framework.js
- lib/build/framework/utils.d.ts
- lib/build/framework/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/awsLambda/framework.ts
- lib/ts/framework/custom/framework.ts
- lib/ts/framework/fastify/framework.ts
- lib/ts/framework/koa/framework.ts
- lib/ts/framework/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/framework/crossFramework.testgen.js
- test/framework/crossframework/repeatedResponseHeader.test.js
- test/framework/loopback-server/index.js
- test/framework/loopback-server/index.ts
- De-duplicate entries in set headers even if `allowDuplicateKey` is true
- Make sure we overwrite old cookies
-   https://github.com/supertokens/supertokens-golang/pull/384/files
Added test described in slack thread (https://supertokens.slack.com/archives/C03J31QAQLC/p1697639483542429)
N/A
- …
> fix: repeated headers/entries in access-control-expose-headers

- lib/build/framework/fastify/index.d.ts
- lib/build/framework/utils.d.ts
- lib/build/recipe/multifactorauth/types.d.ts
- lib/ts/recipe/multifactorauth/types.ts
- test/with-typescript/index.ts
feat: remove distinction between built-in and custom factors
-   https://github.com/supertokens/supertokens-core/issues/554#issuecomment-1770369583
N/A
N/A
-   [ ] add an icon on …
> feat: remove distinction between built-in and custom factors

- CHANGELOG.md
- examples/aws/with-emailpassword/test/helpers/lambda-layer.sh
- lib/build/recipe/thirdparty/providers/apple.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/thirdparty/providers/apple.ts
- lib/ts/version.ts
- package-lock.json
- package.json
This PR removes usage of `crypto` library. This will enable us to support Apple OAuth on other runtime environments like Cloudflare workers.
I have tested Apple OAuth flow manually on web.
-   [x] Had installed and ran the pre-commit …
> feat: Remove crypto usage

- CHANGELOG.md
- lib/build/recipe/thirdparty/providers/linkedin.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/thirdparty/providers/linkedin.ts
- lib/ts/version.ts
- package-lock.json
- package.json
This PR updates the LinkedIn OAuth implementation as per the [recent changes.](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin-v2?context=linkedin%2Fconsumer%2Fcontext#authenticating-members)
-   https://github.com/supertokens/supertokens-node/issues/751
Tested manually.
-   [ ] If new …
> fix: LinkedIn OAuth #751

- CHANGELOG.md
- lib/build/recipe/dashboard/api/userdetails/userPut.js
- lib/build/recipe/emailpassword/api/generatePasswordResetToken.js
- lib/build/recipe/emailpassword/api/passwordReset.js
- lib/build/recipe/emailpassword/api/signin.js
- lib/build/recipe/emailpassword/api/signup.js
- lib/build/recipe/emailpassword/api/utils.d.ts
- lib/build/recipe/emailpassword/api/utils.js
- lib/build/recipe/emailpassword/recipeImplementation.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/api/userdetails/userPut.ts
- lib/ts/recipe/emailpassword/api/generatePasswordResetToken.ts
- lib/ts/recipe/emailpassword/api/passwordReset.ts
- lib/ts/recipe/emailpassword/api/signin.ts
- lib/ts/recipe/emailpassword/api/signup.ts
- lib/ts/recipe/emailpassword/api/utils.ts
- lib/ts/recipe/emailpassword/recipeImplementation.ts
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/emailpassword/signupFeature.test.js
- test/with-typescript/index.ts
Adds userContext to validate function in the form field validators, so that users can read other form fields from the request body whilst validating one form field.
Added a tests in email password recipe to check other form field and return an error
TODO …
> Adds user context to validate function

- CHANGELOG.md
- lib/build/framework/custom/framework.js
- lib/build/framework/custom/nodeHeaders.d.ts
- lib/build/framework/custom/nodeHeaders.js
- lib/ts/framework/custom/framework.ts
- lib/ts/framework/custom/nodeHeaders.ts
Add&use custom impl for Headers class when no built-in is available
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-node/4865/workflows/9f3722bd-3070-454e-80e8-f7a019e4d8b5/jobs/2441
Already tested
N/A …
> fix: use custom impl for Headers class when no built-in is available

- CHANGELOG.md
- lib/build/framework/custom/nodeHeaders.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/custom/nodeHeaders.ts
- lib/ts/version.ts
- package-lock.json
- package.json
remove http dep to fix app dir support
-   
Manually tested
N/A
-   [x] Issue this PR against the latest non released version …
> fix: remove http dep to fix app dir support

- .circleci/config_continue.yml
- package-lock.json
- package.json
- test/fetch-polyfill.js
This PR reverts the docker images for every other test other than unit as those were failing with the newer images.
-   In …
> fix: Update docker images + polyfill fetch by node-fetch for tests

- .circleci/setupAndTestWithFreeCore.sh
This PR attempts to add fetch polyfill before running unit tests with mocha.
-   [ ] Had run `npm …
> fix: add fetch polyfill before running unit tests

- test/nextjs.test.js
This PR replaces getSetCookie method by getAll('Set-Cookie') as `node-fetch` doesn't support it yet.
- …
> fix: replace getSetCookie method by getAll('Set-Cookie')

- CHANGELOG.md
- lib/build/recipe/session/sessionRequestFunctions.js
- lib/ts/recipe/session/sessionRequestFunctions.ts
- test/auth-modes.test.js
`createNewSession` now defaults to the value of the `st-auth-mode` header (if available) if the configured `getTokenTransferMethod` returns `any`.
-   https://discordapp.com/channels/603466164219281420/1195351655093370880
Added tests that check the output of `createNewSession` if:
- `getTokenTransferMethod` returns any
- `st-auth-mode` is: `cookie`, `header`, or not set
N/A
-   [x] Had …
> fix: default to st-auth-mode if getTokenTransferMethod returns any in createNewSession

- CHANGELOG.md
- lib/build/recipe/dashboard/api/implementation.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/api/implementation.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/dashboard/dashboardGet.test.js
Fixes dashboard connection URI path.
Previously we used to return only the domain of the normalised connectionURI without the path provided by the user in Supertokens init config. So this change will also include the path followed by the connectionURL domain to the frontend...
- Wrote unit tests and manually retested the whole dashboard again.
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if …
> fix: dashboard connection uri path.

- lib/build/recipe/dashboard/api/getTenantLoginMethodsInfo.d.ts
- lib/build/recipe/dashboard/api/getTenantLoginMethodsInfo.js
- lib/ts/recipe/dashboard/api/getTenantLoginMethodsInfo.ts
use firstFactors in the dashboard apis, taking directly from the `getLoginMethods` implementation
-   
Manual testing:
- works without initializing MFA recipe (or multitenancy)
- takes firstFactors from the tenant config if exists
- prioritizes firstFactor from tenant config over MFA init
-   In …
> feat: use firstFactors in the dashboard apis

- CHANGELOG.md
- lib/build/recipe/accountlinking/recipe.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/accountlinking/recipe.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/accountlinking-with-session/passwordlessapis.test.js
-   We now allow sign in/up even if the session user is conflicting with the current sign in/up (because of the email verification status)
-   This makes use-cases where an secondary factor (i.e.: otp-email) is also used as a means of verification.
-   https://github.com/supertokens/supertokens-auth-react/actions/runs/8345716229
Duplicated many of the test cases for the consume code api for create code api.
N/A
-   [x] Had …
> fix: allow signing up/in even if the session user is unverified if the sign in will verify it

- CHANGELOG.md
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/accountlinking/userstructure.test.js
The SDK used to assume that the FDI header would always be `X.Y`. But that assumption is not correct since the header can be `X.Y,X1.Y1` and so on.
Added a few tests with multiple fdi versions in the header
-   [ ] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, …
> fixes FDI header parsing logic

- CHANGELOG.md
- lib/build/framework/request.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/request.ts
- lib/ts/version.ts
- package-lock.json
- package.json
handle getFormData returning FormData type
-   [Discord thread](https://discord.com/channels/603466164219281420/1239393137596698624)
Manual testing
N/A
-   [x] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, `createProvider` function.
-   [x] add an icon on the …
> fix: handle getFormData returning FormData type

- test/session.test.js
> fix: Add a test to check session cookies are cleared if refresh api is called with an expired access token

- .circleci/setupAndTestWithAuthReact.sh
- test/auth-react-server/index.js
> ci: fix testing with older auth-react versions

- test/auth-react-server/index.js
> ci: fix backwards compatibility code for older versions

- .circleci/authReact.sh
- .circleci/config_continue.yml
- .circleci/generateConfig.sh
- .circleci/website.sh
> ci: parallelize based on FDI versions

- CHANGELOG.md
- lib/build/recipe/thirdparty/providers/configUtils.js
- lib/build/recipe/thirdparty/providers/utils.d.ts
- lib/build/recipe/thirdparty/providers/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/thirdparty/providers/configUtils.ts
- lib/ts/recipe/thirdparty/providers/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/thirdparty/provider.config.test.js
> fix: thirdparty recursion and confif reference issues

- CHANGELOG.md
- lib/build/recipe/thirdparty/providers/configUtils.js
- lib/build/recipe/thirdparty/providers/utils.d.ts
- lib/build/recipe/thirdparty/providers/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/thirdparty/providers/configUtils.ts
- lib/ts/recipe/thirdparty/providers/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/thirdparty/provider.config.test.js
> fix: thirdparty recursion and config reference issues

- package.json
add the exports in package.json to support esm import for js and ts
This pull request addresses issue [#783](https://github.com/supertokens/supertokens-node/issues/783) by adding [subpath patterns](https://nodejs.org/api/packages.html#subpath-patterns) exports to the package.json file. These exports support ESM (ECMAScript Modules) imports for both JavaScript and TypeScript files, improving compatibility and ease of use for developers. Now, imports like import Session from "supertokens-node/recipe/session"; can be used without specifying the index.js file explicitly.
-   [Link to issue #783](https://github.com/supertokens/supertokens-node/issues/783)
-   [Link to issue #459](https://github.com/supertokens/supertokens-node/issues/459)
1. Update the package.json file with the provided …
> feat: supporting esm import

- lib/build/querier.js
- lib/build/recipe/oauth2/OAuth2Client.d.ts
- lib/build/recipe/oauth2/OAuth2Client.js
- lib/build/recipe/oauth2/index.d.ts
- lib/build/recipe/oauth2/index.js
- lib/build/recipe/oauth2/recipe.js
- lib/build/recipe/oauth2/recipeImplementation.d.ts
- lib/build/recipe/oauth2/recipeImplementation.js
- lib/build/recipe/oauth2/types.d.ts
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/ts/querier.ts
- lib/ts/recipe/oauth2/OAuth2Client.ts
- lib/ts/recipe/oauth2/index.ts
- lib/ts/recipe/oauth2/recipe.ts
- lib/ts/recipe/oauth2/recipeImplementation.ts
- lib/ts/recipe/oauth2/types.ts
- lib/ts/utils.ts
- test/oauth2/oauth2client.test.js
- test/utils.js
This PR adds the `OAuth2Client` class and also a recipe function to create OAuth2Client by calling the Hydra API.
-   In …
> feat: Add a recipe function to create OAuth2Client

- CHANGELOG.md
- lib/build/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
In #835 we had added a workaround to retry request without the `cache` field if it was not available. We were not awaiting the response and prevents the catch block from catching the error.
For some reason it worked fine locally and even on CF (for sometime) until it started breaking recently. Adding `await` fixes the issue.
-   Along with the associated …
> fix: error handling in doFetch

- CHANGELOG.md
- lib/build/recipe/session/constants.d.ts
- lib/build/recipe/session/constants.js
- lib/build/recipe/session/utils.js
- lib/ts/recipe/session/constants.ts
- lib/ts/recipe/session/utils.ts
We decided to update the cookie expiry to 1 year because - 
1. Some browsers cap the max expiry to 400 days. See [this](https://developer.chrome.com/blog/cookie-max-age-expires#:~:text=With%20this%20change%2C%20Chrome%20caps,set%20to%20400%20days%20instead) for info.
2. Our docs mention that access token cookie expiry is 1 year.
-   [ ] `coreDriverInterfaceSupported.json` file has …
> fix: update access token cookie expiry to 1 year

- lib/build/querier.js
- lib/build/recipe/oauth2/api/auth.js
- lib/build/recipe/oauth2/recipeImplementation.js
- lib/ts/querier.ts
- lib/ts/recipe/oauth2/api/auth.ts
- lib/ts/recipe/oauth2/recipeImplementation.ts
- package-lock.json
- package.json
- test/test-server/src/index.ts
- test/test-server/src/oauth2.ts
> fix: OAuth2 fixes and test-server updates

- CHANGELOG.md
- lib/build/recipe/passwordless/recipeImplementation.js
- lib/ts/recipe/passwordless/recipeImplementation.ts
- test/test-server/src/passwordless.ts
- call isEmailChangeAllowed in pwless updateUser
- updated changelog
-   
Adding tests in a separate PR
-   [x] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, `createProvider` function.
-   [x] add an icon on the user management dashboard.
-   [x] Issue this PR …
> feat: call isEmailChangeAllowed in pwless updateUser

- test/test-server/src/index.ts
- test/test-server/src/session.ts
- test/test-server/src/utils.ts
- Supports calling functions on the session object through the test API
- Adds some support for transferring claims and claim validators through the test API (full support requires further work in verifySession and maybe createNewSession)
- https://github.com/supertokens/backend-sdk-testing/pull/22
- https://github.com/supertokens/backend-sdk-testing/issues/16
Test only changes
Test only changes …
> test: move the session object and claims to the BE sdk server

- CHANGELOG.md
This PR updates the changelog for the change done in #878. 
-   In …
> fix: Update changelog

- lib/build/recipeModule.d.ts
- lib/build/recipeModule.js
- lib/build/supertokens.js
- lib/ts/recipeModule.ts
- lib/ts/supertokens.ts
The API request path may or may not include the `tenantId`.  The `returnAPIIdIfCanHandleRequest` function handles both the cases. Currently, the `middleware` function simply calls the first recipe it matches. However, there is a chance that other recipes may have an exact match.
This PR updates the `middlware` such that we prefer an exact match.
-   [ ] …
> fix: Prefer exact api path match in the middleware

- .circleci/config.yml
- .circleci/config_continue.yml
- .circleci/doBackendSDKTests.sh
- .circleci/setupAndTestBackendSDKWithFreeCore.sh
- CHANGELOG.md
- lib/build/recipe/multifactorauth/multiFactorAuthClaim.d.ts
- lib/build/recipe/multifactorauth/multiFactorAuthClaim.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/multifactorauth/multiFactorAuthClaim.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/test-server/src/accountlinking.ts
- test/test-server/src/emailpassword.ts
- test/test-server/src/passwordless.ts
- test/test-server/src/session.ts
- test/test-server/src/thirdparty.ts
- test/test-server/src/utils.ts
> fix: test server compatible with 1.17/2.0

- CHANGELOG.md
- lib/build/recipe/accountlinking/recipe.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/accountlinking/recipe.ts
- lib/ts/version.ts
- package-lock.json
- package.json
Bugfix
-   https://supertokens.slack.com/archives/C051BN9QJUX/p1723036267092849
Added a test to [backend-sdk-testing](https://github.com/supertokens/backend-sdk-testing/pull/36)
N/A
-   [x] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, `createProvider` function. …
> fix: make shouldDoAutomaticAccountLinking properly get the primary user when linking to oldest user

- lib/build/recipe/oauth2client/types.d.ts
- lib/build/recipe/oauth2client/utils.js
- lib/build/recipe/oauth2provider/OAuth2Client.d.ts
- lib/build/recipe/oauth2provider/index.js
- lib/build/recipe/oauth2provider/types.d.ts
- lib/ts/recipe/oauth2client/types.ts
- lib/ts/recipe/oauth2client/utils.ts
- lib/ts/recipe/oauth2provider/OAuth2Client.ts
- lib/ts/recipe/oauth2provider/index.ts
- lib/ts/recipe/oauth2provider/types.ts
This PR makes the `clientSecret` type optional wherever applicable. 
-   In …
> fix: make clientSecret optional

- CHANGELOG.md
- lib/build/recipe/thirdparty/providers/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/thirdparty/providers/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
Improve thirdParty response logging to help debug JSON parsing issues.
-   In …
> fix: thirdparty debug logging

- CHANGELOG.md
- lib/build/recipe/emailpassword/api/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/emailpassword/api/utils.ts
- lib/ts/version.ts
- package.json
- test/emailpassword/signupFeature.test.js
This PR aims to improve the form field validation in emailpassword to allow for optional form fields to be truly optional and not have to send empty values. It looks like the rest of the recipes use the UserMetadata recipe to store extra information.
- https://github.com/supertokens/supertokens-node/issues/300
- https://github.com/supertokens/supertokens-auth-react/issues/638
Added a test case to check the functionality of optional fields missing in the payload does not result in an error
Not sure which section of the docs talks about the behaviour of optional fields currently, can update there once this implementation is completed
-   [x] …
> [WIP] feat: improve form validation

- CHANGELOG.md
- lib/build/recipe/emailpassword/api/implementation.js
- lib/build/recipe/emailpassword/api/utils.d.ts
- lib/build/recipe/emailpassword/api/utils.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/ts/recipe/emailpassword/api/generatePasswordResetToken.ts
- lib/ts/recipe/emailpassword/api/implementation.ts
- lib/ts/recipe/emailpassword/api/passwordReset.ts
- lib/ts/recipe/emailpassword/api/signin.ts
- lib/ts/recipe/emailpassword/api/signup.ts
- lib/ts/recipe/emailpassword/api/utils.ts
- lib/ts/recipe/emailpassword/types.ts
- test/emailpassword/passwordreset.test.js
- test/emailpassword/signinFeature.test.js
- test/emailpassword/signupFeature.test.js
- test/with-typescript/index.ts
Makes the internal type of formField values to be `unknown` instead of `string`. Also adds test for signup/password reset API's when they get non string type of values for email/password.
> PS: Updated the bad input error for email/password being invalid to keep it same as Go/Python SDK's
> NOTE: Did not update Changelog as that was updated in the previous PR to indicate that `any` support is added for formField values.
- `signup`, `signin` and `passwordReset` tests for emailpassword should pass.
-   Along with the associated …
> fix: Add changes to support unknown type in formField values

- lib/build/utils.js
- lib/ts/utils.ts
- package-lock.json
- test/utils.test.js
This commit fixes the updated domain parse util function (that uses tldts) to make sure all tests pass.
Tests were failing as a side effect of #930 due to some behavioural changes between `psl` and `tldts`.
Both `config.test.js` and `utils.test.js` should pass
-   [x] Had …
> fix: failing tests for domain parse util function

- CHANGELOG.md
- lib/build/recipe/emailverification/recipe.js
- lib/build/recipe/emailverification/recipeImplementation.js
- lib/build/recipe/session/index.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/emailverification/recipe.ts
- lib/ts/recipe/emailverification/recipeImplementation.ts
- lib/ts/recipe/session/index.ts
- lib/ts/version.ts
- package-lock.json
- package.json
-   Fixes an issue where revoking sessions for a specific tenant didn't work well
-   Fixes an issue where the automatic session revocation after linking didn't work across all tenants
-   Issue reported by a user over email
Tests added in backend-sdk-testing [PR](https://github.com/supertokens/backend-sdk-testing/pull/41)
N/A
-   [x] If …
> fix: fix the session revocation throwing when email verification links in a non-default tenant

- CHANGELOG.md
- lib/build/recipe/accountlinking/recipe.d.ts
- lib/build/recipe/emailpassword/api/implementation.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/accountlinking/recipe.ts
- lib/ts/recipe/emailpassword/api/implementation.ts
- lib/ts/version.ts
- package-lock.json
- package.json
> fix: password reset flows should allow some cases with no primary user and ep user existing

- .circleci/config.yml
- lib/build/recipe/oauth2provider/api/implementation.js
- lib/build/recipe/oauth2provider/recipeImplementation.js
- lib/build/recipe/oauth2provider/types.d.ts
- lib/ts/recipe/oauth2provider/api/implementation.ts
- lib/ts/recipe/oauth2provider/recipeImplementation.ts
- lib/ts/recipe/oauth2provider/types.ts
> fix: self review test fixes

- .gitignore
- CHANGELOG.md
- lib/build/recipe/totp/api/implementation.js
- lib/build/recipe/totp/api/removeDevice.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/totp/api/implementation.ts
- lib/ts/recipe/totp/api/removeDevice.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/test-server/src/testFunctionMapper.ts
> fix: validate MFA claim before allowing TOTP device removal

- .circleci/config.yml
- .circleci/config_continue.yml
- .circleci/setupAndTestBackendSDKWithFreeCore.sh
- .circleci/setupAndTestWithAuthReact.sh
- .circleci/setupAndTestWithFreeCore.sh
- .circleci/setupAndTestWithFrontend.sh
This PR updates the circle CI related test run files to use circleCI for running tests in order to achieve partial re-run functionality.
- Tests should run fine on CircleCI
- Failed tests should be partially re-runnable through CircleCI
[Reference workflow](https://app.circleci.com/pipelines/gh/supertokens/supertokens-node/6412)
-   In …
> feat: Add changes to run tests using circle ci for partial reruns

- lib/ts/recipe/webauthn/api/implementation.ts
- lib/ts/recipe/webauthn/index.ts
- lib/ts/recipe/webauthn/types.ts
This PR updates the credential types for signup & signin endpoints based on the payload returned by native webauthn library that we are using in web-js (which can be considered as a safe source of truth).
-   [x] Had installed and ran …
> fix: types for signin and signup for webauthn

- CHANGELOG.md
- lib/build/recipe/oauth2provider/api/utils.d.ts
- lib/build/recipe/oauth2provider/api/utils.js
- lib/build/recipe/oauth2provider/types.d.ts
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/oauth2provider/api/utils.ts
- lib/ts/recipe/oauth2provider/types.ts
- lib/ts/version.ts
- package-lock.json
- package.json
> fix: cookies type in oauth2provider

- CHANGELOG.md
- lib/build/recipe/thirdparty/providers/custom.js
- lib/build/recipe/thirdparty/providers/utils.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/thirdparty/providers/custom.ts
- lib/ts/recipe/thirdparty/providers/utils.ts
- lib/ts/recipe/thirdparty/types.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/thirdparty/oidc.test.js
This PR adds support for inferring whether pkce should be used or not based on the OIDC response.
All OIDC related tests and existing tests should pass
-   [ ] If new thirdparty provider …
> feat: inferring pkce based on OIDC response

- test/thirdparty/authorisationUrlFeature.test.js
- test/thirdparty/provider.test.js
Fixes an unit test that was affected due to addition of auto inferring use of PKCE.
All tests should pass …
> fix: failing authorisation unit test

- CHANGELOG.md
- lib/build/recipe/session/cookieAndHeaders.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/session/cookieAndHeaders.ts
- lib/ts/version.ts
- package-lock.json
- package.json
Backport of #1009
- All tests should pass
-   [ ] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, …
> fix: [v20.1] session cookie parsing optimizations

- CHANGELOG.md
- lib/build/recipe/webauthn/api/implementation.js
- lib/build/recipe/webauthn/api/registerCredential.js
- lib/build/recipe/webauthn/types.d.ts
- lib/ts/recipe/webauthn/api/implementation.ts
- lib/ts/recipe/webauthn/api/registerCredential.ts
- lib/ts/recipe/webauthn/types.ts
> fix: Add required recipeUserId field in registerCredential API
