- lib/build/recipe/emailpassword/api/signin.d.ts
- lib/build/recipe/emailpassword/api/signin.js
- lib/build/recipe/emailpassword/api/signup.d.ts
- lib/build/recipe/emailpassword/constants.d.ts
- lib/build/recipe/emailpassword/constants.js
- lib/build/recipe/emailpassword/coreAPICalls.d.ts
- lib/build/recipe/emailpassword/coreAPICalls.js
- lib/build/recipe/emailpassword/error.d.ts
- lib/build/recipe/emailpassword/error.js
- lib/build/recipe/emailpassword/index.d.ts
- lib/build/recipe/emailpassword/index.js
- lib/build/recipe/emailpassword/recipe.d.ts
- lib/build/recipe/emailpassword/recipe.js
- lib/ts/recipe/emailpassword/api/signin.ts
- lib/ts/recipe/emailpassword/constants.ts
- lib/ts/recipe/emailpassword/coreAPICalls.ts
- lib/ts/recipe/emailpassword/error.ts
- lib/ts/recipe/emailpassword/index.ts
- lib/ts/recipe/emailpassword/recipe.ts
- test/emailpassword/signinFeature.test.js
- https://github.com/supertokens/supertokens-node/issues/20
- https://github.com/supertokens/frontend-driver-interface/issues/1
- https://github.com/supertokens/core-driver-interface/issues/1
- Adds `signIn`, `getUserById`, `getUserByEmail` functions.
- Adds default sign in API
- Adds tests todos for sign in
- None
> implements signin API and related functions

- lib/build/recipe/emailpassword/api/signout.d.ts
- lib/build/recipe/emailpassword/api/signout.js
- lib/build/recipe/emailpassword/constants.d.ts
- lib/build/recipe/emailpassword/constants.js
- lib/build/recipe/emailpassword/recipe.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/recipe/emailpassword/utils.js
- lib/build/recipe/session/index.d.ts
- lib/build/recipe/session/index.js
- lib/build/recipe/session/sessionClass.d.ts
- lib/build/recipe/session/sessionClass.js
- lib/ts/recipe/emailpassword/api/signout.ts
- lib/ts/recipe/emailpassword/recipe.ts
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/recipe/emailpassword/utils.ts
- lib/ts/recipe/session/index.ts
- lib/ts/recipe/session/sessionClass.ts
- test/emailpassword/signoutFeature.test.js
- https://github.com/supertokens/supertokens-node/issues/34
- https://github.com/supertokens/supertokens-node/issues/18
- Adds sign up API
- Write test TODOs
- Changes exported type of Session recipe to fix exporting the `SessionContainer` type
- None
> completes signout API & fixes SessionContainer exported type

- lib/build/recipe/emailpassword/api/emailExists.d.ts
- lib/build/recipe/emailpassword/api/emailExists.js
- lib/build/recipe/emailpassword/constants.d.ts
- lib/build/recipe/emailpassword/recipe.js
- lib/build/utils.js
- lib/ts/recipe/emailpassword/api/emailExists.ts
- lib/ts/recipe/emailpassword/constants.ts
- lib/ts/recipe/emailpassword/recipe.ts
- lib/ts/utils.ts
- test/emailpassword/emailExists.test.js
- https://github.com/supertokens/supertokens-node/issues/47
None
> Email exists API

- test/emailpassword/emailExists.test.js
- test/emailpassword/passwordreset.test.js
- test/emailpassword/signinFeature.test.js
- test/emailpassword/signoutFeature.test.js
- test/emailpassword/signupFeature.test.js
- #47 
- Fixes to previous tests(added response status checks)
- Tests added:
- emailExists tests:
- email exists
- email does not exist
- pass an invalid (syntactically) email and check that you get exists: false
- pass an unnormalised email, and check that you get exists true
- do not pass email
- pass an array instead of string in the email
- none
> Added Email Exists tests

- test/emailpassword/emailExists.test.js
- #47 
- Tests added:
- emailExists tests:
- disable the email exists API, and check that calling it returns a 404.
- none
> Added additional email exists test

- .circleci/config.yml
- .circleci/doTests.sh
- .circleci/setupAndTestWithAuthReact.sh
- #46 
- changes .circleci/config.yaml, .circleci/doTests.sh and added setupAndTestWithAuthReact.sh,  to run the supertokens-auth-react tests
- none
> circle ci changes for running supertokens-auth-react tests

- lib/build/recipe/session/faunadb/sessionRecipe.js
- lib/build/recipe/session/faunadb/types.d.ts
- lib/ts/recipe/session/faunadb/sessionRecipe.ts
- lib/ts/recipe/session/faunadb/types.ts
> Improve types for FaunaDB session

- lib/build/recipe/thirdParty/api/authorisationUrl.js
- lib/build/recipe/thirdParty/api/signinup.js
- lib/build/recipe/thirdParty/providers/apple.js
- lib/build/recipe/thirdParty/providers/facebook.js
- lib/build/recipe/thirdParty/providers/github.js
- lib/build/recipe/thirdParty/providers/google.js
- lib/build/recipe/thirdParty/types.d.ts
- lib/build/recipe/thirdParty/utils.d.ts
- lib/build/recipe/thirdParty/utils.js
- lib/ts/recipe/thirdParty/api/authorisationUrl.ts
- lib/ts/recipe/thirdParty/api/signinup.ts
- lib/ts/recipe/thirdParty/providers/apple.ts
- lib/ts/recipe/thirdParty/providers/facebook.ts
- lib/ts/recipe/thirdParty/providers/github.ts
- lib/ts/recipe/thirdParty/providers/google.ts
- lib/ts/recipe/thirdParty/types.ts
- lib/ts/recipe/thirdParty/utils.ts
- redirectURI will be as request body param in singinup API
- bug fix in authorisationUrlAPI where the authorisationUrl was wrongly generated
- not setting redirect_uri param during authorisationUrlAPI
> removing function that generates redirect uri on backend

- lib/build/recipe/thirdParty/providers/apple.js
- lib/build/recipe/thirdParty/providers/facebook.js
- lib/build/recipe/thirdParty/providers/github.js
- lib/build/recipe/thirdParty/providers/google.js
- lib/build/utils.js
- lib/ts/recipe/thirdParty/providers/apple.ts
- lib/ts/recipe/thirdParty/providers/facebook.ts
- lib/ts/recipe/thirdParty/providers/github.ts
- lib/ts/recipe/thirdParty/providers/google.ts
- lib/ts/utils.ts
- test/thirdparty/authorisationUrlFeature.test.js
- test/thirdparty/config.test.js
- test/thirdparty/provider.test.js
- test/thirdparty/signinupFeature.test.js
- test/thirdparty/signoutFeature.test.js
- test/thirdparty/users.test.js
- test/utils.js
- basic tests added for third party recipe
- list of test todos added wherever required
> tests added for thirdparty recipe

- test/querier.test.js
- test/session.test.js
- test/thirdpartyemailpassword/authorisationUrlFeature.test.js
- test/thirdpartyemailpassword/config.test.js
- test/thirdpartyemailpassword/emailExists.test.js
- test/thirdpartyemailpassword/emailverify.test.js
- test/thirdpartyemailpassword/signinFeature.test.js
- test/thirdpartyemailpassword/signoutFeature.test.js
- test/thirdpartyemailpassword/signupFeature.test.js
- test/utils.js
added basic tests for `thirdpartyemailpassword` recipe
> adding tests for thirdpartyemailpasword recipe

- test/config.test.js
added test that checks if the api version loaded and the handshake info loaded from the cache are correct or not
> new test added

- CHANGELOG.md
- lib/build/recipe/emailpassword/api/signin.js
- lib/build/recipe/emailpassword/api/signup.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/recipe/emailpassword/types.js
- lib/build/recipe/emailpassword/utils.js
- lib/build/recipe/thirdpartyemailpassword/recipe.js
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/ts/recipe/emailpassword/api/signin.ts
- lib/ts/recipe/emailpassword/api/signup.ts
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/recipe/emailpassword/utils.ts
- lib/ts/recipe/thirdpartyemailpassword/recipe.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
- lib/ts/recipe/thirdpartyemailpassword/utils.ts
- test/emailpassword/signinFeature.test.js
- test/emailpassword/signupFeature.test.js
> add post sign in callback to all recipes

- CHANGELOG.md
- lib/build/supertokens.d.ts
- lib/build/supertokens.js
- lib/build/types.d.ts
- lib/build/types.js
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/supertokens.ts
- lib/ts/types.ts
- lib/ts/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/config.test.js
Related to https://github.com/supertokens/supertokens-core/issues/234
> Adds apiWebProxyPath

- test/emailpassword/emailverify.test.js
- test/emailpassword/override.test.js
- test/nextjs.test.js
- test/sessionExpress.test.js
- test/thirdparty/override.test.js
- test/thirdpartyemailpassword/override.test.js
> tests added to test function/api overriding

- CHANGELOG.md
- lib/build/recipe/session/accessToken.d.ts
- lib/build/recipe/session/accessToken.js
- lib/build/recipe/session/jwt.d.ts
- lib/build/recipe/session/jwt.js
- lib/build/recipe/session/recipeImplementation.d.ts
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionFunctions.js
- lib/build/recipe/session/types.d.ts
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/session/accessToken.ts
- lib/ts/recipe/session/jwt.ts
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionFunctions.ts
- lib/ts/recipe/session/types.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/session.test.js
- test/utils.js
Related to issue: https://github.com/supertokens/supertokens-node/issues/136
> Getsession function fix

- CHANGELOG.md
- lib/build/framework/awsLambda/framework.d.ts
- lib/build/framework/awsLambda/framework.js
- lib/build/framework/fastify/framework.d.ts
- lib/build/framework/fastify/framework.js
- lib/build/framework/hapi/framework.d.ts
- lib/build/framework/hapi/framework.js
- lib/build/framework/koa/framework.d.ts
- lib/build/framework/koa/framework.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/awsLambda/framework.ts
- lib/ts/framework/fastify/framework.ts
- lib/ts/framework/hapi/framework.ts
- lib/ts/framework/koa/framework.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- updated `sendHTMLResponse` and `getFormData` functions for frameworks
- for fastify, documentation needs to be updated to inform user to add `fastify-formbody` plugin.
> updated `sendHTMLResponse` and `getFormData` functions for frameworks

- CHANGELOG.md
- test/passwordless/apis.test.js
- test/passwordless/config.test.js
- test/passwordless/recipeFunctions.test.js
- test/utils.js
Adds tests for passwordless
-   https://github.com/supertokens/supertokens-node/issues/223
-   [x] …
> Adds passwordless tests

- CHANGELOG.md
- test/passwordless/apis.test.js
- test/passwordless/config.test.js
- test/passwordless/recipeFunctions.test.js
Changes to consumeCode tests, other fixs
- none
-   [ ] Had …
> Passwordless test changes

- .circleci/setupAndTestWithAuthReact.sh
- test/auth-react-server/index.js
Integration tests changes with auth-react
> adds integration tests changes

- CHANGELOG.md
- coreDriverInterfaceSupported.json
- lib/build/index.d.ts
- lib/build/index.js
- lib/build/supertokens.d.ts
- lib/build/supertokens.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/index.ts
- lib/ts/supertokens.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/emailpassword/deleteUser.test.js
Adds delete user
- https://github.com/supertokens/supertokens-core/issues/341
Unit tests
Done
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater …
> Delete user nodejs

- test/passwordless/apis.test.js
- test/passwordless/config.test.js
- test/passwordless/recipeFunctions.test.js
Adds passwordless test fixs and additional passwordless tests
-   In …
> Passwordless tests

- CHANGELOG.md
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/index.js
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/index.ts
- test/thirdpartyemailpassword/signupFeature.test.js
Fixes issue https://github.com/supertokens/supertokens-node/issues/244
-   https://github.com/supertokens/supertokens-node/issues/244
Added a unit test for this
Not required …
> Throws an error in case user tries to update email / password of a third party user

- CHANGELOG.md
- test/thirdpartypasswordless/api.test.js
- test/thirdpartypasswordless/authorisationUrlFeature.test.js
- test/thirdpartypasswordless/config.test.js
- test/thirdpartypasswordless/getUsersByEmailFeature.test.js
- test/thirdpartypasswordless/override.test.js
- test/thirdpartypasswordless/provider.test.js
- test/thirdpartypasswordless/recipeFunctions.test.js
- test/thirdpartypasswordless/signinupFeature.test.js
- test/thirdpartypasswordless/signoutFeature.test.js
- test/thirdpartypasswordless/users.test.js
- test/utils.js
Adds tests for the ThirdPartyPasswordless Recipe
-   https://github.com/supertokens/for-zenhub/issues/102
-   In …
> test: Adds thirdpartypasswordless tests

- CHANGELOG.md
- lib/build/recipe/thirdpartyemailpassword/api/emailPasswordAPIImplementation.js
- lib/build/recipe/thirdpartyemailpassword/api/implementation.js
- lib/build/recipe/thirdpartyemailpassword/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.js
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/emailPasswordRecipeImplementation.js
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/index.js
- lib/build/recipe/thirdpartyemailpassword/recipeImplementation/thirdPartyRecipeImplementation.js
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/ts/recipe/thirdpartyemailpassword/api/emailPasswordAPIImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/api/implementation.ts
- lib/ts/recipe/thirdpartyemailpassword/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/emailPasswordRecipeImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/thirdPartyRecipeImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
Renames a few functions in tpep recipe to make them more user friendly
-   https://github.com/supertokens/supertokens-node/issues/219
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git …
> refactor!: renames functions in tpep

- lib/build/recipe/passwordless/emaildelivery/services/backwardCompatibility/index.d.ts
- lib/build/recipe/passwordless/emaildelivery/services/smtp/index.d.ts
- lib/build/recipe/passwordless/emaildelivery/services/smtp/index.js
- lib/build/recipe/passwordless/emaildelivery/services/smtp/passwordlessLogin.d.ts
- lib/build/recipe/passwordless/emaildelivery/services/smtp/serviceImplementation.d.ts
- lib/build/recipe/passwordless/emaildelivery/services/smtp/serviceImplementation.js
- lib/build/recipe/passwordless/recipe.d.ts
- lib/build/recipe/passwordless/types.d.ts
- lib/build/recipe/thirdparty/emaildelivery/services/smtp/index.d.ts
- lib/build/recipe/thirdparty/emaildelivery/services/smtp/index.js
- lib/build/recipe/thirdpartyemailpassword/emaildelivery/services/smtp/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/emaildelivery/services/smtp/index.js
- lib/ts/recipe/passwordless/emaildelivery/services/backwardCompatibility/index.ts
- lib/ts/recipe/passwordless/emaildelivery/services/smtp/index.ts
- lib/ts/recipe/passwordless/emaildelivery/services/smtp/passwordlessLogin.ts
- lib/ts/recipe/passwordless/emaildelivery/services/smtp/serviceImplementation.ts
- lib/ts/recipe/passwordless/recipe.ts
- lib/ts/recipe/passwordless/types.ts
- lib/ts/recipe/thirdparty/emaildelivery/services/smtp/index.ts
- lib/ts/recipe/thirdpartyemailpassword/emaildelivery/services/smtp/index.ts
- SMTP service class for thirdpartyemailpassword, thirdparty and passwordless recipes
-   #274
> refactor: email sending service, SMTP class PR

- lib/build/logger.js
- lib/build/recipe/session/recipe.js
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionFunctions.js
- lib/build/supertokens.js
- lib/build/utils.js
- lib/ts/logger.ts
- lib/ts/recipe/session/recipe.ts
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionFunctions.ts
- lib/ts/supertokens.ts
- lib/ts/utils.ts
Adds debug log messages so that debugging is easier
- https://github.com/supertokens/for-zenhub/issues/111
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` …
> feat: Adds debug log messages

- .github/helpers/.gitignore
- .github/helpers/package.json
- .github/workflows/pre-commit-hook-run.yml
- .github/workflows/tests-pass-check-pr.yml
- package.json
Adds:
- pre commit check hook
- running tests hook
> ci: adds pre commit gh action - testing

- CHANGELOG.md
- lib/build/ingredients/smsdelivery/services/supertokens.d.ts
- lib/build/ingredients/smsdelivery/services/supertokens.js
- lib/build/recipe/passwordless/emaildelivery/services/smtp/passwordlessLogin.js
- lib/build/recipe/passwordless/smsdelivery/services/backwardCompatibility/index.js
- lib/build/recipe/passwordless/smsdelivery/services/index.d.ts
- lib/build/recipe/passwordless/smsdelivery/services/supertokens/index.d.ts
- lib/build/recipe/passwordless/smsdelivery/services/supertokens/index.js
- lib/build/recipe/thirdpartypasswordless/smsdelivery/services/index.d.ts
- lib/build/recipe/thirdpartypasswordless/smsdelivery/services/index.js
- lib/build/recipe/thirdpartypasswordless/smsdelivery/services/supertokens/index.d.ts
- lib/build/recipe/thirdpartypasswordless/smsdelivery/services/supertokens/index.js
- lib/ts/ingredients/smsdelivery/services/supertokens.ts
- lib/ts/recipe/passwordless/emaildelivery/services/smtp/passwordlessLogin.ts
- lib/ts/recipe/passwordless/smsdelivery/services/backwardCompatibility/index.ts
- lib/ts/recipe/passwordless/smsdelivery/services/index.ts
- lib/ts/recipe/passwordless/smsdelivery/services/supertokens/index.ts
- lib/ts/recipe/thirdpartypasswordless/smsdelivery/services/index.ts
- lib/ts/recipe/thirdpartypasswordless/smsdelivery/services/supertokens/index.ts
- test/with-typescript/index.ts
- supertokens sms service added
- sms backward compatibility default function will first try to query supertokens sms service without passing the service key. If the service throws 429 error response, we'll simply console log the input.
> feat: supertokens sms delivery service

- package-lock.json
- recipe/emailpassword/emaildelivery/index.js
- test/emailpassword/emailDelivery.test.js
- test/passwordless/emailDelivery.test.js
- test/thirdparty/emailDelivery.test.js
- test/thirdpartyemailpassword/emailDelivery.test.js
- test/thirdpartypasswordless/emailDelivery.test.js
- added test for email delivery ingredients
-   #274
> test: email delivery ingredient tests added

- lib/build/recipe/passwordless/smsdelivery/services/backwardCompatibility/index.js
- lib/ts/recipe/passwordless/smsdelivery/services/backwardCompatibility/index.ts
- test/passwordless/smsDelivery.test.js
- test/thirdpartypasswordless/smsDelivery.test.js
- test/utils.js
- added tests for sms delivery ingredient
-   #274
> test: added tests for sms delivery ingredient

- test/utils.js
- pid bug fix in test/utils.js
> test: bug fix in test utils.js

- CHANGELOG.md
- lib/build/framework/hapi/framework.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/hapi/framework.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/framework/hapi.test.js
Fixes duplicate route bug for hapi framework
> fix: routes bug fix in hapi plugin

- test/frontendIntegration/index.js
- added `/update-jwt-with-handle` POST API for frontend integration testing
> refactor: frontend intergartion server update

- lib/build/recipe/thirdpartyemailpassword/emaildelivery/services/backwardCompatibility/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/emaildelivery/services/backwardCompatibility/index.js
- lib/ts/recipe/thirdpartyemailpassword/emaildelivery/services/backwardCompatibility/index.ts
- refactored backward compatibility service changes for TPEP
> refactor: BackwardCompatibilityService changes for TPEP

- lib/build/recipe/emailpassword/api/implementation.js
- lib/build/recipe/emailpassword/passwordResetFunctions.js
- lib/build/recipe/emailverification/api/implementation.js
- lib/build/recipe/emailverification/emailVerificationFunctions.js
- lib/build/recipe/passwordless/api/implementation.js
- lib/build/recipe/passwordless/emaildelivery/services/backwardCompatibility/index.js
- lib/build/recipe/passwordless/smsdelivery/services/backwardCompatibility/index.js
- lib/build/recipe/passwordless/smsdelivery/services/supertokens/index.js
- lib/ts/recipe/emailpassword/api/implementation.ts
- lib/ts/recipe/emailpassword/passwordResetFunctions.ts
- lib/ts/recipe/emailverification/api/implementation.ts
- lib/ts/recipe/emailverification/emailVerificationFunctions.ts
- lib/ts/recipe/passwordless/api/implementation.ts
- lib/ts/recipe/passwordless/emaildelivery/services/backwardCompatibility/index.ts
- lib/ts/recipe/passwordless/smsdelivery/services/backwardCompatibility/index.ts
- lib/ts/recipe/passwordless/smsdelivery/services/supertokens/index.ts
> fix: additional logging for email and sms service

- lib/build/ingredients/emaildelivery/types.d.ts
- lib/build/ingredients/smsdelivery/index.js
- lib/build/ingredients/smsdelivery/types.d.ts
- lib/build/recipe/emailverification/index.d.ts
- lib/build/recipe/emailverification/index.js
- lib/build/recipe/emailverification/types.d.ts
- lib/build/recipe/passwordless/types.d.ts
- lib/ts/ingredients/emaildelivery/types.ts
- lib/ts/ingredients/smsdelivery/index.ts
- lib/ts/ingredients/smsdelivery/types.ts
- lib/ts/recipe/emailverification/index.ts
- lib/ts/recipe/emailverification/types.ts
- lib/ts/recipe/passwordless/types.ts
- test/passwordless/smsDelivery.test.js
- https://github.com/supertokens/supertokens-node/pull/274#discussion_r879686217
- https://github.com/supertokens/supertokens-node/pull/274#discussion_r881947592
- https://github.com/supertokens/supertokens-node/pull/274#discussion_r885241221
-   #274
> refactor: code review changes

- lib/build/recipe/passwordless/smsdelivery/services/backwardCompatibility/index.js
- lib/build/recipe/passwordless/smsdelivery/services/twilio/passwordlessLogin.js
- lib/ts/recipe/passwordless/smsdelivery/services/backwardCompatibility/index.ts
- lib/ts/recipe/passwordless/smsdelivery/services/twilio/passwordlessLogin.ts
- passwordless sms body
- console message when free quota limit is reached
-   #274
> refactor: passwordless sms body

- lib/build/recipe/emailverification/emaildelivery/services/smtp/emailVerify.js
- lib/build/recipe/passwordless/emaildelivery/services/smtp/passwordlessLogin.js
- lib/build/recipe/passwordless/smsdelivery/services/twilio/passwordlessLogin.js
- lib/ts/recipe/emailverification/emaildelivery/services/smtp/emailVerify.ts
- lib/ts/recipe/passwordless/emaildelivery/services/smtp/passwordlessLogin.ts
- lib/ts/recipe/passwordless/smsdelivery/services/twilio/passwordlessLogin.ts
- email and sms content refactored
-   #274
> refactor: Email and sms templates updated

- lib/build/recipe/usermetadata/recipe.js
- lib/build/recipe/userroles/index.d.ts
- lib/build/recipe/userroles/index.js
- lib/build/recipe/userroles/recipe.d.ts
- lib/build/recipe/userroles/recipe.js
- lib/build/recipe/userroles/recipeImplementation.d.ts
- lib/build/recipe/userroles/recipeImplementation.js
- lib/build/recipe/userroles/types.d.ts
- lib/build/recipe/userroles/types.js
- lib/build/recipe/userroles/utils.d.ts
- lib/build/recipe/userroles/utils.js
- lib/ts/recipe/usermetadata/recipe.ts
- lib/ts/recipe/userroles/index.ts
- lib/ts/recipe/userroles/recipe.ts
- lib/ts/recipe/userroles/recipeImplementation.ts
- lib/ts/recipe/userroles/utils.ts
- test/utils.js
Adds recipe implementation for user roles
-   https://github.com/supertokens/supertokens-node/pull/324/files
-   In …
> Adds userrole recipe implementation

- test/passwordless/emailDelivery.test.js
- test/passwordless/smsDelivery.test.js
- test/thirdpartypasswordless/emailDelivery.test.js
- test/thirdpartypasswordless/smsDelivery.test.js
- new emailDelivery and smsDelivery tests added for resend code api for passwordless and thirdpartypasswordless api
> test: new tests added for email and sms resend api

- CHANGELOG.md
- lib/build/recipe/session/index.d.ts
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionClass.js
- lib/build/recipe/session/sessionFunctions.d.ts
- lib/build/recipe/session/sessionFunctions.js
- lib/build/recipe/session/types.d.ts
- lib/build/recipe/session/with-jwt/recipeImplementation.js
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionClass.ts
- lib/ts/recipe/session/sessionFunctions.ts
- lib/ts/recipe/session/types.ts
- lib/ts/recipe/session/with-jwt/recipeImplementation.ts
- test/framework/fastify.test.js
- test/framework/hapi.test.js
- test/framework/koa.test.js
- test/session.test.js
- test/sessionExpress.test.js
> Next breaking change

- lib/build/postSuperTokensInitCallbacks.js
- lib/build/recipe/emailverification/index.d.ts
- lib/build/recipe/emailverification/index.js
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionClass.js
- lib/build/recipe/session/utils.d.ts
- lib/build/recipe/session/utils.js
- lib/ts/postSuperTokensInitCallbacks.ts
- lib/ts/recipe/emailverification/index.ts
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionClass.ts
- lib/ts/recipe/session/utils.ts
- test/emailpassword/emailDelivery.test.js
- test/emailpassword/emailverify.test.js
- test/framework/fastify.test.js
- test/session/claims/primitiveClaim.test.js
- test/session/claims/removeClaim.test.js
- test/session/claims/setClaimValue.test.js
- test/session/claims/verifySession.test.js
- test/thirdparty/signinupFeature.test.js
- test/thirdpartyemailpassword/emailDelivery.test.js
- test/thirdpartyemailpassword/emailverify.test.js
- test/thirdpartyemailpassword/signupFeature.test.js
- test/thirdpartypasswordless/emailDelivery.test.js
- test/thirdpartypasswordless/recipeFunctions.test.js
- test/thirdpartypasswordless/signinupFeature.test.js
- test/utils.js
- Fixed smaller issues
- Made the email param optional in user-facing email verification functions
- Updated tests to work with new claims
- Adding new tests may be done in a separate PR
-   
-   [x] Changes to the …
> test(sessionclaims): update tests

- lib/build/recipe/dashboard/api/implementation.js
- lib/build/recipe/dashboard/api/usersGet.d.ts
- lib/build/recipe/dashboard/api/usersGet.js
- lib/build/recipe/dashboard/utils.js
- lib/ts/recipe/dashboard/api/implementation.ts
- lib/ts/recipe/dashboard/api/usersGet.ts
- lib/ts/recipe/dashboard/utils.ts
- Adds an API for getting the list of users for the dashboard
- Modifies the returned HTML from the dashboard API to include responsiveness meta information
-   ...
...
... …
> feat: Add users list API and modify dashboard HTML

- lib/build/recipe/dashboard/api/usersCountGet.d.ts
- lib/build/recipe/dashboard/api/usersCountGet.js
- lib/build/recipe/dashboard/constants.d.ts
- lib/build/recipe/dashboard/recipe.js
- lib/build/recipe/dashboard/utils.js
- lib/ts/recipe/dashboard/api/usersCountGet.ts
- lib/ts/recipe/dashboard/constants.ts
- lib/ts/recipe/dashboard/recipe.ts
- lib/ts/recipe/dashboard/utils.ts
- Adds the `/api/users/count` API to the Dashboard recipe
-   In …
> feat: Add users count API

- CHANGELOG.md
- lib/build/recipe/thirdparty/api/implementation.js
- lib/build/recipe/thirdparty/index.d.ts
- lib/build/recipe/thirdparty/recipeImplementation.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/build/recipe/thirdpartypasswordless/index.d.ts
- lib/build/recipe/thirdpartypasswordless/types.d.ts
- lib/ts/recipe/thirdparty/api/implementation.ts
- lib/ts/recipe/thirdparty/index.ts
- lib/ts/recipe/thirdparty/recipeImplementation.ts
- lib/ts/recipe/thirdparty/types.ts
- lib/ts/recipe/thirdpartyemailpassword/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/index.ts
- lib/ts/recipe/thirdpartyemailpassword/recipeImplementation/thirdPartyRecipeImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
- lib/ts/recipe/thirdpartypasswordless/index.ts
- lib/ts/recipe/thirdpartypasswordless/recipeImplementation/index.ts
- lib/ts/recipe/thirdpartypasswordless/recipeImplementation/thirdPartyRecipeImplementation.ts
- lib/ts/recipe/thirdpartypasswordless/types.ts
- test/thirdparty/getUsersByEmailFeature.test.js
- test/thirdpartyemailpassword/emailDelivery.test.js
- test/thirdpartyemailpassword/getUsersByEmailFeature.test.js
- test/thirdpartyemailpassword/signupFeature.test.js
- test/thirdpartypasswordless/emailDelivery.test.js
- test/thirdpartypasswordless/getUsersByEmailFeature.test.js
- test/thirdpartypasswordless/recipeFunctions.test.js
- test/userroles/claims.test.js
The signInUp function takes isVerified as well in the email object - but that is not really used by the core anymore, so i removed that param and instead just made email input a string.
> Signinup function cleanup

- lib/build/framework/hapi/framework.js
- lib/ts/framework/hapi/framework.ts
- test/framework/hapi.test.js
- test/useridmapping/recipeTests/thirdpartyemailpassword.test.js
- fix user id mapping test fixes (email as an object)
- fix hapi integration not handling token theft detected
CI build failure
N/A
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch …
> fix: 12.0 test failures

- test/emailpassword/emailverify.test.js
skip deleted user test in email verification before CDI2.10
-   
N/A
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest …
> test: delete user cdi version

- CHANGELOG.md
- lib/build/recipe/session/recipe.js
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionClass.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/session/recipe.ts
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionClass.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- clear cookies unauthorised changes
-   To know which one it is, run find the latest released tag (`git tag`) in …
> refactor: clear cookies unauthorised changes

- CHANGELOG.md
- lib/build/recipe/emailverification/emailVerificationClaim.js
- lib/build/recipe/session/claimBaseClasses/primitiveArrayClaim.d.ts
- lib/build/recipe/session/claimBaseClasses/primitiveArrayClaim.js
- lib/build/recipe/session/claimBaseClasses/primitiveClaim.d.ts
- lib/build/recipe/session/claimBaseClasses/primitiveClaim.js
- lib/build/recipe/userroles/permissionClaim.js
- lib/build/recipe/userroles/userRoleClaim.js
- lib/ts/recipe/emailverification/emailVerificationClaim.ts
- lib/ts/recipe/session/claimBaseClasses/primitiveArrayClaim.ts
- lib/ts/recipe/session/claimBaseClasses/primitiveClaim.ts
- lib/ts/recipe/userroles/permissionClaim.ts
- lib/ts/recipe/userroles/userRoleClaim.ts
- test/session/claims/primitiveArrayClaim.test.js
- test/session/claims/primitiveClaim.test.js
Remove default max age from claims
- 
Updated tests
N/A, this is not mentioned in docs
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …
> feat: remove default max age from claims

- CHANGELOG.md
- README.md
- lib/build/recipe/thirdparty/providers/google.js
- lib/build/recipe/thirdparty/providers/googleWorkspaces.js
- lib/ts/recipe/thirdparty/providers/google.ts
- lib/ts/recipe/thirdparty/providers/googleWorkspaces.ts
- test/thirdparty/provider.test.js
- test/thirdpartypasswordless/provider.test.js
Updated google token endpoint
-   [ ] ~~`coreDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in `lib/ts/version.ts`~~
-   [ ] ~~`frontendDriverInterfaceSupported.json` file has been updated (if needed)~~
-   To know which one it is, run find the latest released tag (`git tag`) …
> fix: updated google token endpoint

- lib/build/recipe/dashboard/api/userdetails/userEmailVerifyGet.d.ts
- lib/build/recipe/dashboard/api/userdetails/userEmailVerifyGet.js
- lib/build/recipe/dashboard/api/userdetails/userGet.d.ts
- lib/build/recipe/dashboard/api/userdetails/userGet.js
- lib/build/recipe/dashboard/api/userdetails/userMetadataGet.d.ts
- lib/build/recipe/dashboard/api/userdetails/userMetadataGet.js
- lib/build/recipe/dashboard/api/userdetails/userSessionsGet.d.ts
- lib/build/recipe/dashboard/api/userdetails/userSessionsGet.js
- lib/build/recipe/dashboard/constants.d.ts
- lib/build/recipe/dashboard/constants.js
- lib/build/recipe/dashboard/recipe.js
- lib/build/recipe/dashboard/types.d.ts
- lib/build/recipe/dashboard/utils.d.ts
- lib/build/recipe/dashboard/utils.js
- lib/build/recipe/thirdpartypasswordless/recipe.d.ts
- lib/ts/recipe/dashboard/api/userdetails/userEmailVerifyGet.ts
- lib/ts/recipe/dashboard/api/userdetails/userGet.ts
- lib/ts/recipe/dashboard/api/userdetails/userMetadataGet.ts
- lib/ts/recipe/dashboard/api/userdetails/userSessionsGet.ts
- lib/ts/recipe/dashboard/constants.ts
- lib/ts/recipe/dashboard/recipe.ts
- lib/ts/recipe/dashboard/types.ts
- lib/ts/recipe/dashboard/utils.ts
- Add user information GET API
- Add user email verify GET API
- Add user metadata GET API
- Add user sessions GET API
None
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch …
> feat: Add GET APIs for user details changed to the dashboard

- test/sessionExpress.test.js
Adds a few tests for different situations of revoking a session during refreshing
-  https://github.com/supertokens/supertokens-node/issues/418
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest …
> Session refreshing revoke tests

- lib/build/recipe/thirdparty/api/implementation.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/build/recipe/thirdpartyemailpassword/api/implementation.js
- lib/build/recipe/thirdpartyemailpassword/api/thirdPartyAPIImplementation.js
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/build/recipe/thirdpartypasswordless/api/implementation.js
- lib/build/recipe/thirdpartypasswordless/api/thirdPartyAPIImplementation.js
- lib/build/recipe/thirdpartypasswordless/types.d.ts
- lib/ts/recipe/thirdparty/api/implementation.ts
- lib/ts/recipe/thirdparty/types.ts
- lib/ts/recipe/thirdpartyemailpassword/api/implementation.ts
- lib/ts/recipe/thirdpartyemailpassword/api/thirdPartyAPIImplementation.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
- lib/ts/recipe/thirdpartypasswordless/api/implementation.ts
- lib/ts/recipe/thirdpartypasswordless/api/thirdPartyAPIImplementation.ts
- lib/ts/recipe/thirdpartypasswordless/types.ts
- thirdparty interface changes regarding account-linking
> thirdparty interface changes regarding account-linking

- CHANGELOG.md
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/version.ts
- package-lock.json
- package.json
Related to https://github.com/supertokens/supertokens-node/issues/455
> fixes a few dependency versions

- lib/build/recipe/accountlinking/types.d.ts
- lib/build/supertokens.js
- lib/ts/recipe/accountlinking/recipe.ts
- lib/ts/recipe/accountlinking/types.ts
- lib/ts/supertokens.ts
- interface updates regarding account linking
> feat: Account linking interface update

- README.md
Add download stats badge
-   [ ] Had installed and ran the …
> feat: Add download stats badge

- .circleci/setupAndTestWithAuthReact.sh
- .circleci/setupAndTestWithFrontend.sh
- lib/build/recipe/session/with-jwt/recipeImplementation.js
- lib/build/recipe/session/with-jwt/sessionClass.js
- lib/ts/recipe/session/with-jwt/recipeImplementation.ts
- lib/ts/recipe/session/with-jwt/sessionClass.ts
- test/frontendIntegration/index.html
Add missing website test helper
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-node/2875/workflows/f08b979c-3003-4924-9b04-831dbf888347/jobs/1257
N/A
N/A …
> test: add missing website test helper

- test/config.test.js
> chore: Fix config test to account for dashboard changes

- CHANGELOG.md
- lib/build/framework/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/framework/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/nextjs.test.js
fix: form parsing of apple sign-ins in nextjs
-   #496 
Updated tests to better match actual use
N/A, bugfix
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose …
> fix: form parsing of apple sign-ins in nextjs

- lib/build/recipe/accountlinking/index.d.ts
- lib/build/recipe/accountlinking/index.js
- lib/build/recipe/accountlinking/recipe.d.ts
- lib/build/recipe/accountlinking/recipe.js
- lib/build/recipe/accountlinking/recipeImplementation.js
- lib/build/recipe/accountlinking/types.d.ts
- lib/build/recipe/dashboard/types.d.ts
- lib/ts/recipe/accountlinking/index.ts
- lib/ts/recipe/accountlinking/recipe.ts
- lib/ts/recipe/accountlinking/recipeImplementation.ts
- lib/ts/recipe/accountlinking/types.ts
- lib/ts/recipe/dashboard/types.ts
Fixes a buch of issues related to https://github.com/supertokens/supertokens-node/pull/466
> account linking: fixes bugs and refactors

- lib/build/recipe/accountlinking/index.d.ts
- lib/build/recipe/accountlinking/recipe.js
- lib/build/recipe/accountlinking/recipeImplementation.js
- lib/build/recipe/accountlinking/types.d.ts
- lib/ts/recipe/accountlinking/recipe.ts
- lib/ts/recipe/accountlinking/recipeImplementation.ts
- lib/ts/recipe/accountlinking/types.ts
> account linking: removes ANOTHER from canCreatePrimaryUserId status return type

- lib/build/recipe/dashboard/api/implementation.js
- lib/build/recipe/dashboard/api/search/tagsGet.d.ts
- lib/build/recipe/dashboard/api/search/tagsGet.js
- lib/build/recipe/dashboard/api/usersGet.js
- lib/build/recipe/dashboard/constants.d.ts
- lib/build/recipe/dashboard/constants.js
- lib/build/recipe/dashboard/recipe.js
- lib/build/recipe/dashboard/utils.js
- lib/build/supertokens.d.ts
- lib/build/supertokens.js
- lib/ts/recipe/dashboard/api/implementation.ts
- lib/ts/recipe/dashboard/api/search/tagsGet.ts
- lib/ts/recipe/dashboard/api/usersGet.ts
- lib/ts/recipe/dashboard/constants.ts
- lib/ts/recipe/dashboard/recipe.ts
- lib/ts/recipe/dashboard/utils.ts
- lib/ts/supertokens.ts
Adds apis to support dashboard search
- GET /search/tags: returns a list of search tags supported
- https://github.com/supertokens/main-website/issues/1049
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find …
> feat: dashboard search apis

- CHANGELOG.md
- lib/build/recipe/emailverification/emaildelivery/services/smtp/emailVerify.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/emailverification/emaildelivery/services/smtp/emailVerify.ts
- lib/ts/version.ts
- package-lock.json
- package.json
> fix: verify email template

- test/emailpassword/users.test.js
added version check to the test …
> tests: added version check to tests

- lib/build/recipe/emailverification/emailVerificationClaim.js
- lib/build/recipe/multitenancy/allowedDomainsClaim.d.ts
- lib/build/recipe/multitenancy/allowedDomainsClaim.js
- lib/build/recipe/multitenancy/index.d.ts
- lib/build/recipe/multitenancy/index.js
- lib/build/recipe/multitenancy/recipe.d.ts
- lib/build/recipe/multitenancy/recipe.js
- lib/build/recipe/multitenancy/types.d.ts
- lib/build/recipe/session/claimBaseClasses/primitiveArrayClaim.d.ts
- lib/build/recipe/session/claimBaseClasses/primitiveClaim.d.ts
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/types.d.ts
- lib/build/recipe/session/types.js
- lib/build/recipe/userroles/permissionClaim.js
- lib/build/recipe/userroles/userRoleClaim.js
- lib/ts/recipe/emailverification/emailVerificationClaim.ts
- lib/ts/recipe/multitenancy/allowedDomainsClaim.ts
- lib/ts/recipe/multitenancy/index.ts
- lib/ts/recipe/multitenancy/recipe.ts
- lib/ts/recipe/multitenancy/types.ts
- lib/ts/recipe/session/claimBaseClasses/primitiveArrayClaim.ts
- lib/ts/recipe/session/claimBaseClasses/primitiveClaim.ts
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/types.ts
- lib/ts/recipe/userroles/permissionClaim.ts
- lib/ts/recipe/userroles/userRoleClaim.ts
- test/with-typescript/index.ts
- Add `tenantId` param to `fetchValue` function in claims
- Use `tenantId` in allowedDomainsClaim
- Fix allowed domains claim class and filename
-   [ ] Changes to the …
> fix: multitenancy claims

- lib/build/recipe/userroles/index.d.ts
- lib/build/recipe/userroles/index.js
- lib/build/recipe/userroles/permissionClaim.js
- lib/build/recipe/userroles/recipeImplementation.js
- lib/build/recipe/userroles/types.d.ts
- lib/build/recipe/userroles/userRoleClaim.js
- lib/ts/recipe/userroles/index.ts
- lib/ts/recipe/userroles/permissionClaim.ts
- lib/ts/recipe/userroles/recipeImplementation.ts
- lib/ts/recipe/userroles/types.ts
- lib/ts/recipe/userroles/userRoleClaim.ts
- test/userroles/multitenantRole.test.js
Multitenancy implementation for user roles recipe
- …
> fix: multitenancy user roles

- CHANGELOG.md
update/fix migration guide in changelog
-   #601 
N/A Docs only change
N/A Docs only change
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater …
> docs: update/fix migration guide in changelog

- lib/build/recipe/userroles/index.js
- lib/build/recipe/userroles/types.d.ts
- lib/ts/recipe/userroles/index.ts
- lib/ts/recipe/userroles/types.ts
- test/with-typescript/index.ts
> fix: tenantId compulsory in user roles recipe interface

- test/auth-react-server/utils.js
- test/frontendIntegration/index.js
fix: fix/update integration test servers
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-node/3966/workflows/2cf73a97-8958-4e06-b327-53ceb70461e5/jobs/1796
N/A test server update only
N/A test server update only
-   To know which one it is, run …
> fix: fix/update integration test servers

- lib/build/recipe/emailpassword/api/implementation.js
- lib/build/recipe/emailpassword/index.d.ts
- lib/build/recipe/emailpassword/index.js
- lib/build/recipe/emailpassword/utils.d.ts
- lib/build/recipe/emailpassword/utils.js
- lib/build/recipe/thirdpartyemailpassword/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.js
- lib/ts/recipe/emailpassword/api/implementation.ts
- lib/ts/recipe/emailpassword/index.ts
- lib/ts/recipe/emailpassword/utils.ts
- lib/ts/recipe/thirdpartyemailpassword/index.ts
> fix: password reset email

- lib/build/recipe/emailpassword/utils.js
- lib/build/recipe/emailverification/utils.js
- lib/build/recipe/passwordless/utils.js
- lib/build/recipe/thirdpartyemailpassword/index.d.ts
- lib/build/recipe/thirdpartyemailpassword/index.js
- lib/build/recipe/thirdpartyemailpassword/types.d.ts
- lib/build/recipe/thirdpartyemailpassword/utils.js
- lib/build/recipe/thirdpartypasswordless/utils.js
- lib/ts/recipe/thirdpartyemailpassword/index.ts
- lib/ts/recipe/thirdpartyemailpassword/types.ts
-   https://github.com/supertokens/supertokens-node/pull/471
-   [ …
> fix: tenantIdForPasswordPolicy

- lib/build/framework/hapi/framework.js
- lib/build/recipe/dashboard/recipe.d.ts
- lib/build/recipe/dashboard/recipe.js
- lib/ts/framework/hapi/framework.ts
- lib/ts/recipe/dashboard/recipe.ts
- Updates Hapi routing to account for multitenancy
- Update Dashboard API routing to match other recipes
- 
-   In …
> refactor: Update routing logic for Hapi and dashboard recipe to account for multitenancy

- lib/build/recipe/session/index.d.ts
- lib/build/recipe/session/index.js
- lib/build/recipe/session/types.d.ts
- lib/build/recipe/session/utils.js
- lib/ts/recipe/session/index.ts
- lib/ts/recipe/session/types.ts
- lib/ts/recipe/session/utils.ts
- test/with-typescript/index.ts
-   https://github.com/supertokens/supertokens-node/pull/471
-   [ …
> fix: tenant id in get global claim validators

- lib/build/recipe/dashboard/api/listTenants.d.ts
- lib/build/recipe/dashboard/api/listTenants.js
- lib/ts/recipe/dashboard/api/listTenants.ts
> refactor: Remove core config from dashboard tenants list response

- lib/build/recipe/thirdparty/providers/googleWorkspaces.js
- lib/ts/recipe/thirdparty/providers/googleWorkspaces.ts
- test/emailpassword/passwordreset.test.js
- test/framework/awsLambda.withTenantId.test.js
- test/framework/fastify.withTenantId.test.js
- test/framework/hapi.withTenantId.test.js
- test/framework/koa.withTenantId.test.js
- test/framework/loopback.withTenantId.test.js
- test/passwordless/config.test.js
- test/passwordless/recipeFunctions.test.js
- test/thirdparty/multitenancy.test.js
- test/thirdparty/provider.test.js
- test/thirdpartypasswordless/api.test.js
- test/thirdpartypasswordless/authorisationUrlFeature.test.js
- test/thirdpartypasswordless/config.test.js
- test/thirdpartypasswordless/getUsersByEmailFeature.test.js
- test/thirdpartypasswordless/override.test.js
- test/thirdpartypasswordless/provider.test.js
- test/thirdpartypasswordless/recipeFunctions.test.js
- test/thirdpartypasswordless/signinupFeature.test.js
- test/thirdpartypasswordless/signoutFeature.test.js
- test/thirdpartypasswordless/smsDelivery.test.js
- test/thirdpartypasswordless/users.test.js
- test/useridmapping/recipeTests/passwordless.test.js
- test/useridmapping/recipeTests/thirdpartypasswordless.test.js
> fix: tests fixes

- examples/aws/with-emailpassword/README.md
> test: test added for aws lambda example

- test/auth-react-server/index.js
- test/auth-react-server/utils.js
> fix: auth react server

- examples/aws/with-emailpassword/test/basic.test.js
> fix: example test

- .circleci/authReact.sh
- .circleci/website.sh
- lib/build/recipe/multitenancy/allowedDomainsClaim.d.ts
- lib/build/recipe/multitenancy/allowedDomainsClaim.js
- lib/ts/recipe/multitenancy/allowedDomainsClaim.ts
> fix: allowed domain claim and some typos

- test/thirdpartyemailpassword/config.test.js
> fix: unit test

- test/auth-react-server/index.js
The feature flag route in the auth-react-server enabled a few tests which caused this.
-   In …
> fix: ci test fix

- test/frontendIntegration/index.js
> fix: fe test fix

- test/session/accessTokenVersions.test.js
add a test that checks how we handle nullable access token payload props
-   https://github.com/supertokens/supertokens-golang/pull/318/files
Test only change
Test only change
-   [ …
> test: add a test that checks how we handle nullable access token payload props

- CHANGELOG.md
- lib/build/recipe/thirdparty/api/implementation.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/thirdparty/api/implementation.ts
- lib/ts/version.ts
- package-lock.json
- package.json
> fix: apple redirect

- lib/build/recipe/dashboard/api/userdetails/userUnlinkGet.d.ts
- lib/build/recipe/dashboard/api/userdetails/userUnlinkGet.js
- lib/build/recipe/dashboard/constants.d.ts
- lib/build/recipe/dashboard/constants.js
- lib/build/recipe/dashboard/recipe.js
- lib/ts/recipe/dashboard/api/userdetails/userUnlinkGet.ts
- lib/ts/recipe/dashboard/constants.ts
- lib/ts/recipe/dashboard/recipe.ts
- test/accountlinking/passwordlessapis.test.js
> feat: Account unlink endpoint for dashboard

- .gitignore
- CHANGELOG.md
add compatibility section into changelog
-   
N/A
N/A
-   [x] update switch statement in `recipe/thirdparty/providers/configUtils.ts` file, `createProvider` function.
-   [x] add an icon on the user management dashboard.
- …
> chore: add compatibility section into changelog

- CHANGELOG.md
- addDevTag
- lib/build/constants.d.ts
- lib/build/constants.js
- lib/build/querier.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/constants.ts
- lib/ts/querier.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/ratelimiting.test.js
> refactor: Add handling for when Saas returns 429 because of rate limiting

- lib/build/recipe/session/with-jwt/sessionClass.js
- lib/ts/recipe/session/with-jwt/sessionClass.ts
> fix: Fix jwt expiry check

- .circleci/setupAndTestWithAuthReact.sh
> fix; Update CICD

- test/accountlinking/emailpasswordapis.test.js
> test: update tests for prev changes

- CHANGELOG.md
Updated the changelog
-   
N/A
N/A
-   To know which one …
> chore: mention resetPasswordUsingToken changes in the account linking changelog

- test/utils.js
test: fix test util to work with old/normal responses
-   In …
> test: fix test util to work with old/normal responses

- test/config.test.js
test: fix test expectation
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-node/4560/workflows/65670c69-21c4-4e1a-b2a3-86033b4dabdd/jobs/2267
N/A
N/A
-   [ ] …
> test: fix test expectation

- lib/build/recipe/emailverification/emailVerificationClaim.js
- lib/build/recipe/multifactorauth/api/implementation.js
- lib/build/recipe/multifactorauth/index.js
- lib/build/recipe/multifactorauth/multiFactorAuthClaim.d.ts
- lib/build/recipe/multifactorauth/multiFactorAuthClaim.js
- lib/build/recipe/multifactorauth/recipe.js
- lib/build/recipe/multifactorauth/recipeImplementation.js
- lib/build/recipe/multifactorauth/types.d.ts
- lib/build/recipe/multitenancy/allowedDomainsClaim.js
- lib/build/recipe/session/claimBaseClasses/primitiveArrayClaim.d.ts
- lib/build/recipe/session/claimBaseClasses/primitiveClaim.d.ts
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/types.d.ts
- lib/build/recipe/session/types.js
- lib/build/recipe/userroles/permissionClaim.js
- lib/build/recipe/userroles/userRoleClaim.js
- lib/ts/recipe/emailverification/emailVerificationClaim.ts
- lib/ts/recipe/multifactorauth/api/implementation.ts
- lib/ts/recipe/multifactorauth/index.ts
- lib/ts/recipe/multifactorauth/multiFactorAuthClaim.ts
- lib/ts/recipe/multifactorauth/recipe.ts
- lib/ts/recipe/multifactorauth/recipeImplementation.ts
- lib/ts/recipe/multifactorauth/types.ts
- lib/ts/recipe/multitenancy/allowedDomainsClaim.ts
- lib/ts/recipe/session/claimBaseClasses/primitiveArrayClaim.ts
- lib/ts/recipe/session/claimBaseClasses/primitiveClaim.ts
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/types.ts
- lib/ts/recipe/userroles/permissionClaim.ts
- lib/ts/recipe/userroles/userRoleClaim.ts
> refactor: added shouldRefetch + fetchValue building the next array into MFAclaim

- CHANGELOG.md
- lib/build/recipe/dashboard/api/implementation.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/api/implementation.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/dashboard/dashboardGet.test.js
Normalises connectionURI domain before injecting into dashboard raw html string.
This is how changes will reflect on the frontend.
-   In …
> fix: Normalise connectionURI domain.

- examples/aws/with-emailpassword/backend/config.mjs
- examples/aws/with-emailpassword/backend/user.mjs
This PR updates the aws lambda example to match the [latest doc changes.](https://github.com/supertokens/docs/pull/761)
-   [ ] …
> fix: Update aws example docs

- lib/build/recipe/emailpassword/api/implementation.js
- lib/build/recipe/multifactorauth/index.d.ts
- lib/build/recipe/multifactorauth/recipe.d.ts
- lib/build/recipe/multifactorauth/recipe.js
- lib/build/recipe/multifactorauth/recipeImplementation.js
- lib/build/recipe/multifactorauth/types.d.ts
- lib/build/recipe/passwordless/api/implementation.js
- lib/build/recipe/thirdparty/api/implementation.js
- lib/build/recipe/totp/api/implementation.js
- lib/ts/recipe/emailpassword/api/implementation.ts
- lib/ts/recipe/multifactorauth/recipe.ts
- lib/ts/recipe/multifactorauth/recipeImplementation.ts
- lib/ts/recipe/multifactorauth/types.ts
- lib/ts/recipe/passwordless/api/implementation.ts
- lib/ts/recipe/thirdparty/api/implementation.ts
- lib/ts/recipe/totp/api/implementation.ts
- test/mfa/mfa.api.test.js
- test/mfa/mfa.withAccountLinking.test.js
- test/mfa/utils.js
> fix: mfa flow refactor

- lib/build/recipe/multifactorauth/api/implementation.js
- lib/build/recipe/multifactorauth/api/mfaInfo.js
- lib/build/recipe/multifactorauth/multiFactorAuthClaim.d.ts
- lib/build/recipe/multifactorauth/multiFactorAuthClaim.js
- lib/build/recipe/multifactorauth/recipe.js
- lib/build/recipe/multifactorauth/recipeImplementation.js
- lib/build/recipe/multifactorauth/types.d.ts
- lib/ts/recipe/multifactorauth/api/implementation.ts
- lib/ts/recipe/multifactorauth/api/mfaInfo.ts
- lib/ts/recipe/multifactorauth/multiFactorAuthClaim.ts
- lib/ts/recipe/multifactorauth/recipe.ts
- lib/ts/recipe/multifactorauth/recipeImplementation.ts
- lib/ts/recipe/multifactorauth/types.ts
- test/mfa/mfa.api.test.js
> fix: next array

- package-lock.json
- package.json
- test/fetch-polyfill.mjs
This PR upgrades node-fetch to v3 because the earlier version didn't have methods like `Response.json` implemented (required by NextJS). Since, node-fetch v3 is esm only, we had to use `.mjs` extension for the polyfill..
-   [ ] …
> fix: upgrade node-fetch to v3

- .circleci/setupAndTestWithFreeCore.sh
Fixes the fetch poyfill file name. …
> Fix fetch polyfill filename

- package-lock.json
- package.json
- test/fetch-polyfill.mjs
- test/nextjs.test.js
This PR removes node-fetch v3 and uses cross-fetch for the polyfill which underneath the hood uses node-fetch v2. We do need to polyfill Response.json because it is used by Next.js but not present in node-fetch v2.
- …
> fix: use cross-fetch for polyfill

- test/auth-react-server/index.js
- test/frontendIntegration/index.js
Update test servers for CI failures
-   
N/A
N/A
-   To …
> test: update test servers

- test/dashboard/dashboardGet.test.js
test: remove usage of try.supertokens.com from tests
-   In …
> test: remove usage of try.supertokens.com from tests

- CHANGELOG.md
> chore: expand changelog

- CHANGELOG.md
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionFunctions.d.ts
- lib/build/recipe/session/sessionFunctions.js
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionFunctions.ts
- package-lock.json
- test/session/useDynamicSigningKeySwitching.test.js
> fix: backports for core 8.0

- CHANGELOG.md
- lib/build/recipe/session/recipeImplementation.js
- lib/build/recipe/session/sessionFunctions.d.ts
- lib/build/recipe/session/sessionFunctions.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/session/recipeImplementation.ts
- lib/ts/recipe/session/sessionFunctions.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/session/useDynamicSigningKeySwitching.test.js
> fix: backport to core 6.0

- CHANGELOG.md
- lib/build/authUtils.d.ts
- lib/build/authUtils.js
- lib/build/recipe/passwordless/api/implementation.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/authUtils.ts
- lib/ts/recipe/passwordless/api/implementation.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/accountlinking-with-session/passwordlessapis.test.js
- test/accountlinking-with-session/utils.js
- test/mfa/mfa.passwordlessapis.test.js
- test/mfa/utils.js
-   Smaller fixes in `Passwordless`:
-   Fixed an issue in `createCodePOST` where the flowtype wasn't appropriately set in some MFA cases
-   Fixed an interaction with the `firstFactors` config of the `MultiFactorAuth` recipe in `createCodePOST`
-   Fixed an issue in `resendCodePOST` where the email/text message included a magic link when it shouldn't have in some MFA cases
- [Slack thread](https://supertokens.slack.com/archives/C051BN9QJUX/p1711634375184509)
- [Slack thread 2](https://supertokens.slack.com/archives/C051BN9QJUX/p1711634375184509)
- [Slack msg](https://supertokens.slack.com/archives/D02B887A2MQ/p1711534592806949)
Added test:
- flowType checked in MFA createCodePOST response
- type of email sent in MFA resendCodePOST
- flowType + sent email checked in first factor …
> fix: fix mfa interactions with pwless

- lib/build/framework/request.js
- lib/ts/framework/request.ts
add explanation comment for changes in #831
-   
N/A
N/A …
> docs: add explanation comment for changes in 831

- test/session.test.js
> fix: increase wait time to allow access token to expire

- test/auth-react-server/index.js
- test/emailpassword/emailDelivery.test.js
- test/emailpassword/passwordreset.test.js
- test/emailpassword/signoutFeature.test.js
- test/middleware2.test.js
- test/thirdparty/signoutFeature.test.js
> fix: ci issues

- CHANGELOG.md
> chore: fix formatting error in changelog

- .circleci/config.yml
- CHANGELOG.md
- lib/build/recipe/thirdparty/providers/configUtils.js
- lib/ts/recipe/thirdparty/providers/configUtils.ts
> fix: comments and circleci

- CONTRIBUTING.md
> docs: add backend-sdk-testing in the contributing guide

- lib/build/querier.d.ts
- lib/build/querier.js
- lib/build/recipe/oauth2/OAuth2Client.d.ts
- lib/build/recipe/oauth2/OAuth2Client.js
- lib/build/recipe/oauth2/index.d.ts
- lib/build/recipe/oauth2/index.js
- lib/build/recipe/oauth2/recipeImplementation.js
- lib/build/recipe/oauth2/types.d.ts
- lib/build/types.d.ts
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/ts/querier.ts
- lib/ts/recipe/oauth2/OAuth2Client.ts
- lib/ts/recipe/oauth2/index.ts
- lib/ts/recipe/oauth2/recipeImplementation.ts
- lib/ts/recipe/oauth2/types.ts
- lib/ts/types.ts
- lib/ts/utils.ts
- test/oauth2/oauth2client.test.js
This PR adds the recipe functions to update/delete OAuth2Client.
-   In …
> feat: Add recipe functions to update/delete OAuth2Client

- test/test-server/src/index.ts
- test/test-server/src/overrideLogging.ts
add logging to default overrides in test-server
-   
N/A, test only change
N/A, test only change
-   [ ] Issue this PR against …
> test: add logging to default overrides in test-server

- CHANGELOG.md
- lib/build/recipe/thirdparty/providers/activeDirectory.js
- lib/build/recipe/thirdparty/providers/apple.js
- lib/build/recipe/thirdparty/providers/gitlab.js
- lib/build/recipe/thirdparty/providers/google.js
- lib/build/recipe/thirdparty/providers/okta.js
- lib/build/recipe/thirdparty/providers/utils.d.ts
- lib/build/recipe/thirdparty/providers/utils.js
- lib/ts/recipe/thirdparty/providers/activeDirectory.ts
- lib/ts/recipe/thirdparty/providers/apple.ts
- lib/ts/recipe/thirdparty/providers/gitlab.ts
- lib/ts/recipe/thirdparty/providers/google.ts
- lib/ts/recipe/thirdparty/providers/okta.ts
- lib/ts/recipe/thirdparty/providers/utils.ts
> fix: oidc fixes

- .github/workflows/pre-commit-hook-run.yml
- .github/workflows/test-edge-function.yml
- .github/workflows/test-examples.yml
- examples/aws/with-emailpassword/test/helpers/lambda-layer.sh
> fix: PR checks

- lib/build/recipe/dashboard/api/multitenancy/deleteTenant.js
- lib/ts/recipe/dashboard/api/multitenancy/deleteTenant.ts
- test/auth-react-server/utils.js
- test/dashboard/createOrUpdateThirdPartyConfig.test.js
- test/dashboard/deleteThirdPartyConfig.test.js
- test/emailpassword/emailverify.test.js
- test/emailpassword/passwordreset.test.js
- test/utils.js
> fix: cicd tests

- CHANGELOG.md
- lib/build/recipe/dashboard/api/multitenancy/getThirdPartyConfig.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/api/multitenancy/getThirdPartyConfig.ts
- lib/ts/version.ts
- package-lock.json
- package.json
> fix: issue in fetching third party config

- CHANGELOG.md
- lib/build/recipe/dashboard/api/multitenancy/createOrUpdateThirdPartyConfig.d.ts
- lib/build/recipe/dashboard/api/multitenancy/createOrUpdateThirdPartyConfig.js
- lib/build/recipe/dashboard/api/multitenancy/getTenantInfo.js
- lib/build/recipe/dashboard/api/multitenancy/getThirdPartyConfig.js
- lib/build/recipe/multitenancy/api/implementation.js
- lib/build/recipe/thirdparty/providers/configUtils.d.ts
- lib/build/recipe/thirdparty/providers/configUtils.js
- lib/build/recipe/thirdparty/recipeImplementation.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/build/recipe/thirdparty/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/dashboard/api/multitenancy/createOrUpdateThirdPartyConfig.ts
- lib/ts/recipe/dashboard/api/multitenancy/getTenantInfo.ts
- lib/ts/recipe/dashboard/api/multitenancy/getThirdPartyConfig.ts
- lib/ts/recipe/multitenancy/api/implementation.ts
- lib/ts/recipe/thirdparty/providers/configUtils.ts
- lib/ts/recipe/thirdparty/recipeImplementation.ts
- lib/ts/recipe/thirdparty/types.ts
- lib/ts/recipe/thirdparty/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/test-server/src/multitenancy.ts
> feat: updates for SAML dashboard

- lib/build/recipe/oauth2/api/implementation.js
- lib/build/recipe/oauth2/api/utils.d.ts
- lib/build/recipe/oauth2/api/utils.js
- lib/ts/recipe/oauth2/api/implementation.ts
- lib/ts/recipe/oauth2/api/utils.ts
This PR removes the internal redirects in the OAuth2 flow.
-   In …
> fix: Remove internal redirects in the OAuth2 flow

- lib/build/querier.js
- lib/build/recipe/oauth2client/recipeImplementation.js
- lib/build/recipe/oauth2provider/api/implementation.js
- lib/build/recipe/oauth2provider/api/userInfo.js
- lib/build/recipe/oauth2provider/recipeImplementation.js
- lib/build/recipe/oauth2provider/types.d.ts
- lib/ts/querier.ts
- lib/ts/recipe/oauth2client/recipeImplementation.ts
- lib/ts/recipe/oauth2provider/api/implementation.ts
- lib/ts/recipe/oauth2provider/api/userInfo.ts
- lib/ts/recipe/oauth2provider/recipeImplementation.ts
- lib/ts/recipe/oauth2provider/types.ts
This PR contains some minor OAuth2 fixes.
-   [ ] …
> fix: OAuth2 fixes

- test/emailpassword/signinFeature.test.js
Fixes tests related to sign-in functionality for formField validation.
`signin` related tests should pass. …
> Fix failing test related to signin

- examples/next/with-emailpassword/app/api/auth/[...path]/route.ts
- lib/build/customFramework.d.ts
- lib/build/customFramework.js
- lib/build/nextjs.d.ts
- lib/build/nextjs.js
- lib/ts/customFramework.ts
- lib/ts/nextjs.ts
- test/customFramework.test.js
- test/nextjs.test.js
- test/with-typescript/index.ts
> several fixes and refactoring

- lib/build/recipe/session/cookieAndHeaders.js
- lib/ts/recipe/session/cookieAndHeaders.ts
- test/session.test.js
> maybe fixes issue, testing pending

- test/userContext.test.js
Fixes test cases related to userContext for customFramework changes
`userContext.test.js` should pass. …
> fix: userContext-test-for-custom-framework

- test/userContext.test.js
test: add exception for changes introduced in #946  …
> test: add exception for changes introduced in #946

- CHANGELOG.md
- lib/build/recipe/totp/api/removeDevice.js
- lib/ts/recipe/totp/api/removeDevice.ts
- test/test-server/src/testFunctionMapper.ts
> fix: validate MFA claim before allowing TOTP device removal

- lib/build/recipe/webauthn/index.d.ts
- lib/build/recipe/webauthn/index.js
- lib/ts/recipe/webauthn/index.ts
> Add missing update user email export

- .github/workflows/backend-sdk-test.yml
- CHANGELOG.md
- compose.yml
- test/test-server/src/index.ts
- Adds a GHA workflow to run backend-sdk-testing tests
- Updates test server to work with test changes
- Adds missing test endpoint to reset logs
- Adds a docker compose file to run the core
(cherry picked from commit 32db0ad50266a621f196ba86949f64c6f12edfb4)
- #978
-   [ ] …
> ci: backend-sdk-testing (#978)

- .github/workflows/website-test.yml
- CHANGELOG.md
- test/frontendIntegration/index.html
- test/frontendIntegration/index.js
- Adds workflow to run supertokens-website tests
- Updates `frontendIntegration` servers to support test changes
- Adds docker compose file to run core and oauth containers
-   [ ] `frontendDriverInterfaceSupported.json` file has been updated (if …
> ci: website

- .github/workflows/auth-react-test-1.yml
- .github/workflows/backend-sdk-test.yml
- .github/workflows/pipeline-dev-tag.yml
- .github/workflows/pipeline-release-tag.yml
- .github/workflows/website-test.yml
- hooks/populate-hook-constants.sh
> feat: sets up dev/release pipelines

- CHANGELOG.md
- lib/build/recipe/webauthn/api/implementation.js
- lib/build/recipe/webauthn/api/listCredentials.js
- lib/build/recipe/webauthn/api/registerCredential.js
- lib/build/recipe/webauthn/api/removeCredential.js
- lib/ts/recipe/webauthn/api/implementation.ts
- lib/ts/recipe/webauthn/api/listCredentials.ts
- lib/ts/recipe/webauthn/api/registerCredential.ts
- lib/ts/recipe/webauthn/api/removeCredential.ts
- Prevent removal of WebAuthn credentials unless all session claims are satisfied.
- Change how sessions are fetched before listing, removing, and adding WebAuthn credentials
-   [ ] …
> fix: Change how WebAuthn credential management endpoints handle session requirements
